/**
 * Interface strings.
 */
export const strings = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.browse": "Browse internships",
    "nav.applications": "My applications",
    "nav.certificates": "Certificates",
    "nav.faq": "Help and FAQ",
    "nav.notifications": "Notifications",
    "nav.ai": "AI assistant",
    "nav.profile": "My profile",
    "nav.settings": "Settings",
    "nav.post": "Post internship",
    "nav.manage": "Manage internships",
    "nav.applicants": "Applicants",
    "nav.company": "Company profile",
    "nav.certificateReview": "Certificate review",
    "nav.companies": "Companies",
    "nav.internships": "Internships",
    "nav.users": "Users",
    "nav.reports": "Reports",
    "nav.integration": "Integration status",

    "section.inbox": "Inbox",
    "section.yourSearch": "Your search",
    "section.hiring": "Hiring",
    "section.platform": "Platform",
    "section.assistant": "Assistant",
    "section.account": "Account",
    "section.developer": "Developer",

    "action.refresh": "Refresh",
    "action.save": "Save changes",
    "action.cancel": "Cancel",
    "action.close": "Close",
    "action.edit": "Edit",
    "action.view": "View",
    "action.apply": "Apply",
    "action.send": "Send",
    "action.search": "Search",
    "action.signOut": "Sign out",
    "action.markAllRead": "Mark all read",
    "action.markRead": "Mark read",

    "bell.title": "Notifications",
    "bell.empty": "Nothing new.",
    "bell.viewAll": "View all notifications",
    "bell.unread": "unread",

    "lang.label": "Language",
    "lang.english": "English",
    "lang.burmese": "မြန်မာ",

    "theme.label": "Theme",
    "theme.system": "System",
    "theme.light": "Light",
    "theme.dark": "Dark",

    "role.student": "Student",
    "role.employer": "Employer",
    "role.admin": "Administrator",
  },

  my: {
    // --- employer profile ---
    "Department": "ဌာန",
    "Work email": "အလုပ် အီးမေးလ်",
    "Sign-in email": "ဝင်ရောက်ရန် အီးမေးလ်",
    "Contact phone": "ဆက်သွယ်ရန် ဖုန်း",
    "No job title yet": "ရာထူးအမည် မထည့်ရသေးပါ",
    "Not set": "မသတ်မှတ်ရသေးပါ",
    "Shown beside your name to students and administrators.": "ကျောင်းသားများနှင့် စီမံခန့်ခွဲသူများအတွက် သင့်နာမည် ဘေးတွင် ပြပါမည်။",
    "Optional. Your sign-in email is not changed by this.": "ရွေးချယ်နိုင်သည်။ ဝင်ရောက်ရန် အီးမေးလ်ကို ဤအရာက မပြောင်းပါ။",
    "Your recruiter details as students and administrators see them.": "ကျောင်းသားများနှင့် စီမံခန့်ခွဲသူများ မြင်ရမည့် သင့်ခေါ်ယူသူ အချက်အလက်များ။",
    "Your details, photo and company logo.": "သင့်အချက်အလက်များ၊ ဓာတ်ပုံနှင့် ကုမ္ပဏီ လိုဂို။",

    "The logo is changed on the profile edit page.": "လိုဂိုကို ပရိုဖိုင် ပြင်ဆင်သည့် စာမျက်နှာတွင် ပြောင်းနိုင်ပါသည်။",
    "Company logo": "ကုမ္ပဏီ လိုဂို",
    // --- image picker and profile editing ---
    "Use this image?": "ဤပုံကို သုံးမည်လား။",
    "Use this image": "ဤပုံကို သုံးရန်",
    "Choose an image": "ပုံ ရွေးရန်",
    "The image you chose": "သင်ရွေးချယ်ခဲ့သော ပုံ",
    "Nothing changes until you confirm.": "အတည်မပြုမချင်း ဘာမျှ ပြောင်းလဲမည် မဟုတ်ပါ။",
    "Shown to students and administrators beside the company name. JPG or PNG.": "ကုမ္ပဏီအမည် ဘေးတွင် ကျောင်းသားများနှင့် စီမံခန့်ခွဲသူများ မြင်ရပါမည်။ JPG သို့မဟုတ် PNG။",
    "Edit profile": "ပရိုဖိုင် ပြင်ဆင်ရန်",
    "Your details as students and administrators see them.": "ကျောင်းသားများနှင့် စီမံခန့်ခွဲသူများ မြင်ရမည့် သင့်အချက်အလက်များ။",
    "Your details and photo, as students and administrators see them.": "ကျောင်းသားများနှင့် စီမံခန့်ခွဲသူများ မြင်ရမည့် သင့်အချက်အလက်များနှင့် ဓာတ်ပုံ။",

    // --- photo confirmation and company logo ---
    "Use this photo?": "ဤဓာတ်ပုံကို သုံးမည်လား။",
    "Use this photo": "ဤဓာတ်ပုံကို သုံးရန်",
    "It replaces your current photo everywhere your name appears.": "သင့်နာမည် ပေါ်သည့် နေရာတိုင်းရှိ လက်ရှိ ဓာတ်ပုံကို အစားထိုးပါမည်။",
    "Choose a different one": "အခြားတစ်ပုံ ရွေးရန်",
    "The photo you chose": "သင်ရွေးချယ်ခဲ့သော ဓာတ်ပုံ",
    "Change logo": "လိုဂို ပြောင်းရန်",
    "Recruiter details": "ခေါ်ယူသူ အချက်အလက်များ",

    // --- profile pages ---
    "Back to my profile": "ကျွန်ုပ်၏ ပရိုဖိုင်သို့ ပြန်သွားရန်",
    "Loading profile...": "ပရိုဖိုင် ရယူနေသည်...",
    "Full name": "အမည် အပြည့်အစုံ",
    "Shown beside your photo in the users list.": "အသုံးပြုသူ စာရင်းတွင် သင့်ဓာတ်ပုံ ဘေး၌ ပြသပါမည်။",
    "Optional. Useful when another administrator needs to reach you.": "ရွေးချယ်နိုင်သည်။ အခြား စီမံခန့်ခွဲသူတစ်ဦး ဆက်သွယ်လိုသည့်အခါ အသုံးဝင်ပါသည်။",
    "Your email, role and account status cannot be changed from this page.": "သင့်အီးမေးလ်၊ အခန်းကဏ္ဍနှင့် အကောင့်အခြေအနေကို ဤစာမျက်နှာမှ ပြောင်း၍ မရပါ။",
    "The photo is changed on the profile page, and the password in Settings.": "ဓာတ်ပုံကို ပရိုဖိုင် စာမျက်နှာတွင်၊ စကားဝှက်ကို ဆက်တင်များတွင် ပြောင်းပါ။",
    "Not editable here": "ဤနေရာတွင် ပြင်၍ မရပါ",
    "My profile": "ကျွန်ုပ်၏ ပရိုဖိုင်",
    "Name": "အမည်",
    "Never signed in": "တစ်ကြိမ်မျှ မဝင်ရောက်ဖူးပါ",
    "Your details": "သင့်အချက်အလက်များ",
    "Details": "အသေးစိတ်",
    "Photo": "ဓာတ်ပုံ",

    // --- profile photo and account details ---
    "Profile photo": "ပရိုဖိုင် ဓာတ်ပုံ",
    "Shown beside your name wherever it appears. JPG or PNG, up to 5 MB.": "သင့်နာမည် ပေါ်သည့် နေရာတိုင်းတွင် ဘေးတွင် ပြသပါမည်။ JPG သို့မဟုတ် PNG၊ ၅ MB အထိ။",
    "Choose a photo": "ဓာတ်ပုံ ရွေးရန်",
    "Uploading...": "တင်နေသည်...",
    "Remove": "ဖယ်ရှားရန်",
    "Phone": "ဖုန်းနံပါတ်",
    "Not given": "မဖော်ပြထားပါ",
    "Headline": "ခေါင်းစဉ်",
    "University": "တက္ကသိုလ်",
    "Studying": "လေ့လာနေသည်",
    "Job title": "ရာထူးအမည်",
    "Company": "ကုမ္ပဏီ",
    "Industry": "လုပ်ငန်းနယ်ပယ်",
    "Registration number": "မှတ်ပုံတင် နံပါတ်",
    "Location": "တည်နေရာ",

    "Read the full message": "စာအပြည့်အစုံ ဖတ်ရန်",
    "Unread": "မဖတ်ရသေး",
    // --- delete this account ---
    "Delete this account": "ဤအကောင့်ကို ဖျက်ရန်",
    "This cannot be undone": "ဤအရာကို ပြန်ပြင်၍ မရပါ",
    "Deleting removes this account and everything attached to it: your profile, your applications and every certificate you have uploaded. Verified certificates are removed too and would have to be checked again if you register a second time.": "ဖျက်လိုက်ပါက ဤအကောင့်နှင့် ၎င်းနှင့် ဆက်စပ်သမျှ — သင့်ပရိုဖိုင်၊ သင့်လျှောက်လွှာများနှင့် သင်တင်ထားသော လက်မှတ်အားလုံး — ဖယ်ရှားသွားပါမည်။ စိစစ်ပြီးသော လက်မှတ်များပါ ပါသွားပြီး ဒုတိယအကြိမ် မှတ်ပုံတင်ပါက ပြန်လည် စစ်ဆေးရပါမည်။",
    "Registered under the wrong role?": "အခန်းကဏ္ဍ မှားပြီး မှတ်ပုံတင်မိပါသလား။",
    "Delete this account, then register again with the role you meant. A role cannot be changed once chosen, because the profile and its records are tied to it.": "ဤအကောင့်ကို ဖျက်ပြီး ရည်ရွယ်သည့် အခန်းကဏ္ဍဖြင့် ပြန်လည် မှတ်ပုံတင်ပါ။ ပရိုဖိုင်နှင့် ၎င်း၏ မှတ်တမ်းများ ချိတ်ဆက်နေသောကြောင့် တစ်ကြိမ် ရွေးပြီးပါက အခန်းကဏ္ဍ ပြောင်း၍ မရပါ။",
    "Your password": "သင့်စကားဝှက်",
    "Required, because deletion is permanent.": "ဖျက်ခြင်းသည် အပြီးအပိုင် ဖြစ်သောကြောင့် မဖြစ်မနေ လိုအပ်ပါသည်။",
    "Type DELETE to confirm": "အတည်ပြုရန် DELETE ဟု ရိုက်ထည့်ပါ",
    "Delete my account permanently": "ကျွန်ုပ်၏ အကောင့်ကို အပြီးအပိုင် ဖျက်ရန်",
    "Deleting...": "ဖျက်နေသည်...",

    // --- administrator invitation and confirm dialog ---
    "Accept your invitation": "သင့်ဖိတ်ခေါ်မှုကို လက်ခံရန်",
    "Enter the code from your invitation email and choose a password. The account cannot be used until you do.": "ဖိတ်ခေါ်မှု အီးမေးလ်ရှိ ကုဒ်ကို ထည့်ပြီး စကားဝှက် ရွေးချယ်ပါ။ ထိုသို့ မပြုလုပ်မချင်း အကောင့်ကို အသုံးပြု၍ မရပါ။",
    "Invitation code": "ဖိတ်ခေါ်မှု ကုဒ်",
    "Six digits, from the email. It expires 72 hours after it was sent.": "အီးမေးလ်မှ ဂဏန်း ခြောက်လုံး။ ပို့ပြီး ၇၂ နာရီအကြာတွင် သက်တမ်းကုန်ပါမည်။",
    "Choose a password": "စကားဝှက် ရွေးချယ်ပါ",
    "Confirm the password": "စကားဝှက်ကို အတည်ပြုပါ",
    "The two passwords do not match.": "စကားဝှက် နှစ်ခု မကိုက်ညီပါ။",
    "Activate my account": "ကျွန်ုပ်၏ အကောင့်ကို အသက်သွင်းရန်",
    "Setting up...": "စတင် သတ်မှတ်နေသည်...",
    "Your account is ready": "သင့်အကောင့် အဆင်သင့် ဖြစ်ပါပြီ",
    "Sign in with the password you just chose. You have administrator access.": "ယခုရွေးချယ်ခဲ့သော စကားဝှက်ဖြင့် ဝင်ရောက်ပါ။ သင့်တွင် စီမံခန့်ခွဲသူ အခွင့်အရေး ရှိပါသည်။",
    "Go to sign in": "ဝင်ရောက်ရန် စာမျက်နှာသို့",
    "Reason": "အကြောင်းရင်း",
    "Type {word} to confirm": "အတည်ပြုရန် {word} ဟု ရိုက်ထည့်ပါ",
    "Working...": "ဆောင်ရွက်နေသည်...",
    "Issuer not given": "ထုတ်ပေးသူ မဖော်ပြထားပါ",
    "Cancel": "ပယ်ဖျက်ရန်",

    "Certificate review": "လက်မှတ် စိစစ်ခြင်း",
    "Earlier": "အစောပိုင်း",
    "Loading notifications...": "အကြောင်းကြားချက်များ ရယူနေသည်...",

    // --- post an internship ---
    "Matching": "တွဲပေးခြင်း",
    "Approval": "အတည်ပြုချက်",
    "Deadline": "နောက်ဆုံးရက်",
    "Changes": "ပြောင်းလဲမှုများ",
    "Students are matched to vacancies by comparing their recorded skills against the ones you require.": "ကျောင်းသားများ၏ မှတ်တမ်းတင်ထားသော ကျွမ်းကျင်မှုများကို သင် တောင်းဆိုသည်များနှင့် နှိုင်းယှဉ်၍ နေရာများနှင့် တွဲပေးပါသည်။",
    "List three to five skills. A vacancy with none cannot be matched to anybody, and that is the most common reason a listing attracts nothing.": "ကျွမ်းကျင်မှု သုံးခုမှ ငါးခု ဖော်ပြပါ။ တစ်ခုမှ မပါသော နေရာကို မည်သူနှင့်မျှ တွဲပေး၍ မရပါ။ ကြေညာချက်တစ်ခု လျှောက်လွှာ မရရှိခြင်း၏ အဖြစ်များဆုံး အကြောင်းရင်း ဖြစ်သည်။",
    "A vacancy stays a draft until an administrator has approved your company registration.": "စီမံခန့်ခွဲသူက သင့်ကုမ္ပဏီ မှတ်ပုံတင်ခြင်းကို အတည်မပြုမချင်း နေရာမှာ မူကြမ်း အဆင့်တွင် ရှိနေပါမည်။",
    "Write and save it now. Students see it the moment approval comes through, and you are notified when it does.": "ယခု ရေးသား သိမ်းဆည်းပါ။ အတည်ပြုချက် ရသည်နှင့် ကျောင်းသားများ ချက်ချင်း မြင်ရပြီး သင့်ထံလည်း အသိပေးပါမည်။",
    "Once the application deadline passes, students can no longer apply and the vacancy stops appearing in their search.": "လျှောက်လွှာ နောက်ဆုံးရက် ကျော်လွန်ပါက ကျောင်းသားများ လျှောက်၍ မရတော့ဘဲ ၎င်းတို့၏ ရှာဖွေမှုတွင်လည်း ပေါ်တော့မည် မဟုတ်ပါ။",
    "Two to four weeks suits a student term. Leave it empty if you do not want a cut-off at all.": "နှစ်ပတ်မှ လေးပတ်သည် ကျောင်းသား စာသင်ကာလနှင့် သင့်လျော်ပါသည်။ ကန့်သတ်ရက် လုံးဝ မလိုပါက ဗလာထားပါ။",
    "Nothing here is final, and applications already received are kept when you change a vacancy.": "ဤနေရာတွင် အပြီးအပိုင် မဟုတ်ပါ။ နေရာကို ပြောင်းလဲသည့်အခါ လက်ခံရရှိပြီးသော လျှောက်လွှာများ ကျန်ရှိပါသည်။",
    "Publish and refine rather than delay. An unpublished vacancy reaches nobody.": "ဆိုင်းငံ့ထားမည့်အစား ကြေညာပြီးမှ ပြင်ဆင်ပါ။ မကြေညာရသေးသော နေရာသည် မည်သူ့ထံမျှ မရောက်ပါ။",
    "A vacancy takes about five minutes to write.": "နေရာလွတ်တစ်ခု ရေးသားရန် ငါးမိနစ်ခန့် ကြာပါသည်။",
    "Only a title is required. Everything else can be added later, and a vacancy with more detail is matched to more students.": "ခေါင်းစဉ်တစ်ခုသာ မဖြစ်မနေ လိုအပ်ပါသည်။ ကျန်သည်များကို နောက်မှ ဖြည့်နိုင်ပြီး အသေးစိတ် ပိုများသော နေရာသည် ကျောင်းသား ပိုများနှင့် ကိုက်ညီပါသည်။",
    "What happens after you publish": "ကြေညာပြီးနောက် ဖြစ်ပေါ်မည့် အဆင့်များ",
    "You write it": "သင် ရေးသားသည်",
    "Saved as a draft": "မူကြမ်းအဖြစ် သိမ်းဆည်းသည်",
    "Company approved": "ကုမ္ပဏီ အတည်ပြုသည်",
    "An administrator checks it": "စီမံခန့်ခွဲသူက စစ်ဆေးသည်",
    "Students see it": "ကျောင်းသားများ မြင်ရသည်",
    "Matched on required skills": "လိုအပ်သော ကျွမ်းကျင်မှုဖြင့် တွဲပေးသည်",
    "Applications arrive": "လျှောက်လွှာများ ရောက်လာသည်",
    "With verified certificates": "စိစစ်ပြီး လက်မှတ်များနှင့်အတူ",
    "Saving...": "သိမ်းဆည်းနေသည်...",
    "Changes saved.": "ပြောင်းလဲမှုများ သိမ်းဆည်းပြီးပါပြီ။",
    "Internship published successfully.": "အလုပ်သင်နေရာ ကြေညာပြီးပါပြီ။",
    "Internship draft created successfully.": "အလုပ်သင်နေရာ မူကြမ်း ဖန်တီးပြီးပါပြီ။",
    "Unable to create the internship.": "အလုပ်သင်နေရာ ဖန်တီး၍ မရပါ။",
    "Edit internship": "အလုပ်သင်နေရာ ပြင်ဆင်ရန်",
    "Applications already received are kept.": "လက်ခံရရှိပြီးသော လျှောက်လွှာများ ကျန်ရှိပါမည်။",
    "Could not load this internship.": "ဤအလုပ်သင်နေရာကို ရယူ၍ မရပါ။",
    "Progress": "အခြေအနေ",
    "{n} of 3 sections ready": "အပိုင်း ၃ ခုအနက် {n} ခု ပြင်ဆင်ပြီး",
    "Title and description": "ခေါင်းစဉ်နှင့် ဖော်ပြချက်",
    "Location and work mode": "နေရာနှင့် အလုပ်လုပ်ပုံ",
    "A stipend or a closing date": "ထောက်ပံ့ကြေး သို့မဟုတ် ပိတ်ရက်",
    "How students will see it": "ကျောင်းသားများ မြင်ရမည့် ပုံစံ",
    "This updates as you type.": "သင် ရိုက်ထည့်သည်နှင့်အမျှ ပြောင်းလဲပါသည်။",
    "Untitled vacancy": "ခေါင်းစဉ် မရှိသေးသော နေရာ",
    "No description yet.": "ဖော်ပြချက် မရှိသေးပါ။",
    "{n} months": "{n} လ",
    "Closes {d}": "{d} တွင် ပိတ်မည်",
    "No closing date": "ပိတ်ရက် မရှိပါ",
    "Students see it once your company is approved.": "သင့်ကုမ္ပဏီ အတည်ပြုပြီးသည်နှင့် ကျောင်းသားများ မြင်ရပါမည်။",
    "A draft is visible only to you.": "မူကြမ်းကို သင်သာ မြင်ရပါသည်။",
    "Before you start, four things worth knowing.": "မစတင်မီ သိထားသင့်သည့် အချက် လေးချက်။",
    "Start writing the vacancy": "နေရာလွတ် စတင် ရေးသားရန်",
    "Back to my vacancies": "ကျွန်ုပ်၏ နေရာများသို့ ပြန်သွားရန်",
    "Required skills decide who sees it": "လိုအပ်သော ကျွမ်းကျင်မှုများက မည်သူမြင်ရမည်ကို ဆုံးဖြတ်သည်",
    "Students are matched to vacancies by comparing their recorded skills against the ones you require. A vacancy with no required skills cannot be matched to anybody, and is the most common reason a listing attracts nothing.": "ကျောင်းသားများ၏ မှတ်တမ်းတင်ထားသော ကျွမ်းကျင်မှုများကို သင် တောင်းဆိုသည်များနှင့် နှိုင်းယှဉ်၍ နေရာများနှင့် တွဲပေးပါသည်။ လိုအပ်သော ကျွမ်းကျင်မှု မသတ်မှတ်ထားသော နေရာကို မည်သူနှင့်မျှ တွဲပေး၍ မရပါ။ ကြေညာချက်တစ်ခု လျှောက်လွှာ မရရှိခြင်း၏ အဖြစ်များဆုံး အကြောင်းရင်း ဖြစ်သည်။",
    "Your company must be approved first": "သင့်ကုမ္ပဏီကို ဦးစွာ အတည်ပြုရပါမည်",
    "A vacancy stays a draft until an administrator has approved your company registration. You can write and save it now; students will see it as soon as the approval comes through.": "စီမံခန့်ခွဲသူက သင့်ကုမ္ပဏီ မှတ်ပုံတင်ခြင်းကို အတည်မပြုမချင်း နေရာမှာ မူကြမ်း အဆင့်တွင် ရှိနေပါမည်။ ယခု ရေးသား သိမ်းဆည်းနိုင်ပြီး အတည်ပြုချက် ရလျှင် ကျောင်းသားများ ချက်ချင်း မြင်ရပါမည်။",
    "The deadline closes it automatically": "နောက်ဆုံးရက်က အလိုအလျောက် ပိတ်ပေးသည်",
    "Once the application deadline passes, students can no longer apply, and the vacancy stops appearing in their search. Leave it empty if you do not want a cut-off.": "လျှောက်လွှာ နောက်ဆုံးရက် ကျော်လွန်သွားပါက ကျောင်းသားများ လျှောက်၍ မရတော့ဘဲ ၎င်းတို့၏ ရှာဖွေမှုတွင်လည်း ပေါ်တော့မည် မဟုတ်ပါ။ ကန့်သတ်ရက် မလိုပါက ဗလာထားပါ။",
    "You can edit it after publishing": "ကြေညာပြီးနောက် ပြင်ဆင်နိုင်သည်",
    "Nothing here is final. Applications already received are kept when you change a vacancy, so it is better to publish and refine than to delay.": "ဤနေရာတွင် အပြီးအပိုင် မဟုတ်ပါ။ နေရာကို ပြောင်းလဲသည့်အခါ လက်ခံရရှိပြီးသော လျှောက်လွှာများ ကျန်ရှိနေပါသည်။ ထို့ကြောင့် ဆိုင်းငံ့ထားခြင်းထက် ကြေညာပြီးမှ ပြင်ဆင်ခြင်းက ပိုကောင်းပါသည်။",
    "The role": "ရာထူး",
    "What the internship is, and what a student would actually do.": "အလုပ်သင်နေရာမှာ ဘာဖြစ်သည်၊ ကျောင်းသားက အမှန်တကယ် ဘာလုပ်ရမည်။",
    "Where and how": "နေရာနှင့် ပုံစံ",
    "Short answers. Two to a line so the form stays readable.": "အတိုချုံး ဖြေပါ။ ဖတ်ရလွယ်စေရန် တစ်ကြောင်းလျှင် နှစ်ခု ထားပါသည်။",
    "Pay and deadline": "ထောက်ပံ့ကြေးနှင့် နောက်ဆုံးရက်",
    "Leave the deadline empty if you do not want a cut-off.": "ကန့်သတ်ရက် မလိုပါက နောက်ဆုံးရက်ကို ဗလာထားပါ။",
    "Students see this first. Name the role, not the department.": "ကျောင်းသားများ ဤအရာကို ဦးစွာ မြင်ပါသည်။ ဌာနအမည်မဟုတ်ဘဲ ရာထူးအမည်ကို ရေးပါ။",
    "What the internship is for, and what the student would learn.": "အလုပ်သင်နေရာ၏ ရည်ရွယ်ချက်နှင့် ကျောင်းသား သင်ယူရမည့် အရာများ။",
    "Day-to-day tasks. Concrete tasks attract better-matched applicants.": "နေ့စဉ် လုပ်ငန်းတာဝန်များ။ တိကျသော တာဝန်များက ပိုကိုက်ညီသော လျှောက်ထားသူများကို ဆွဲဆောင်ပါသည်။",
    "What a student must already be able to do.": "ကျောင်းသားတစ်ဦး ကြိုတင် တတ်ကျွမ်းထားရမည့် အရာများ။",
    "On-site, remote or hybrid. Students filter on this.": "ရုံးတွင်း၊ အဝေးမှ သို့မဟုတ် ရောနှော။ ကျောင်းသားများ ဤအချက်ဖြင့် စစ်ထုတ်ကြပါသည်။",
    "In months. Leave empty if it is open-ended.": "လအလိုက်။ သတ်မှတ်ချက် မရှိပါက ဗလာထားပါ။",
    "How many students you intend to take.": "လက်ခံရန် ရည်ရွယ်သည့် ကျောင်းသား အရေအတွက်။",
    "A stated stipend, even a small one, attracts more applicants than a blank field.": "အနည်းငယ်မျှသာ ဖြစ်စေကာမူ ဖော်ပြထားသော ထောက်ပံ့ကြေးက ဗလာထားခြင်းထက် လျှောက်ထားသူ ပိုများစေပါသည်။",
    "After this date students can no longer apply and the vacancy stops appearing.": "ဤရက်နောက်ပိုင်း ကျောင်းသားများ လျှောက်၍ မရတော့ဘဲ နေရာလည်း ပေါ်တော့မည် မဟုတ်ပါ။",
    "Draft keeps it hidden. Open publishes it once your company is approved.": "မူကြမ်းသည် ဖုံးကွယ်ထားပါသည်။ ဖွင့်ထားပါက ကုမ္ပဏီ အတည်ပြုပြီးသည်နှင့် ကြေညာပါမည်။",

    // --- role changes and account deletion ---
    "I chose the wrong role. Can I change it?": "အခန်းကဏ္ဍ မှားရွေးမိပါသည်။ ပြောင်း၍ ရပါသလား။",
    "No, and this is deliberate rather than missing. A student account has a student profile beneath it, and an employer account has a company profile pointing at a company record; switching the role would leave one orphaned and the other absent, and every page for the new role would fail. Delete the account in Settings and register again with the role you meant.": "မရပါ။ ဤသည်မှာ ချန်လှပ်ထားခြင်း မဟုတ်ဘဲ ရည်ရွယ်ချက်ရှိရှိ ဖြစ်သည်။ ကျောင်းသား အကောင့်တွင် ကျောင်းသား ပရိုဖိုင် ရှိပြီး၊ အလုပ်ရှင် အကောင့်တွင် ကုမ္ပဏီကို ညွှန်းသော ပရိုဖိုင် ရှိပါသည်။ အခန်းကဏ္ဍ ပြောင်းလျှင် တစ်ခုမှာ ပိုင်ရှင်မဲ့ ဖြစ်ကာ ကျန်တစ်ခုမှာ မရှိတော့ဘဲ အခန်းကဏ္ဍ အသစ်၏ စာမျက်နှာတိုင်း ချွတ်ယွင်းပါမည်။ ဆက်တင်များတွင် အကောင့်ကို ဖျက်ပြီး ရည်ရွယ်သည့် အခန်းကဏ္ဍဖြင့် ပြန်လည် မှတ်ပုံတင်ပါ။",
    "Can I have both a student and an employer account?": "ကျောင်းသားနှင့် အလုပ်ရှင် အကောင့် နှစ်ခုလုံး ရှိနိုင်ပါသလား။",
    "Yes, but they must use different email addresses, because the address is what identifies an account. Sign out of one before signing in to the other. Nothing is shared between them, and an employer account still waits for its company to be approved.": "ရနိုင်ပါသည်။ သို့သော် အီးမေးလ် လိပ်စာ မတူညီရပါမည်။ အကောင့်ကို ခွဲခြားသတ်မှတ်သည်မှာ လိပ်စာဖြစ်သောကြောင့် ဖြစ်သည်။ တစ်ခုမှ ထွက်ပြီးမှ အခြားတစ်ခုသို့ ဝင်ပါ။ ၎င်းတို့အကြား မည်သည့်အရာမျှ မျှဝေခြင်း မရှိပါ။ အလုပ်ရှင် အကောင့်မှာ ကုမ္ပဏီ အတည်ပြုချက်ကို စောင့်ရဆဲ ဖြစ်သည်။",
    "How do I delete my own account?": "ကျွန်ုပ်၏ အကောင့်ကို မည်သို့ ဖျက်ရမလဲ။",
    "Settings, at the bottom, under Delete this account. You need your password and you must type DELETE, because it cannot be undone: the profile, applications and certificates all go with it. If you are the last active administrator the platform refuses, since nobody would then be able to verify a certificate.": "ဆက်တင်များ၏ အောက်ဆုံး၊ ဤအကောင့်ကို ဖျက်ရန် အောက်တွင် ရှိသည်။ စကားဝှက် လိုအပ်ပြီး DELETE ဟု ရိုက်ထည့်ရပါမည်။ ပြန်ပြင်၍ မရသောကြောင့် ဖြစ်သည် — ပရိုဖိုင်၊ လျှောက်လွှာများနှင့် လက်မှတ်များ အားလုံး ပါသွားပါမည်။ သင်သည် နောက်ဆုံး စီမံခန့်ခွဲသူ ဖြစ်ပါက စနစ်က ငြင်းပယ်ပါမည်။ လက်မှတ် စိစစ်နိုင်သူ မကျန်တော့မည် ဖြစ်သောကြောင့် ဖြစ်သည်။",
    "I registered as a student but I meant to register as an employer.": "ကျောင်းသားအဖြစ် မှတ်ပုံတင်မိသော်လည်း အလုပ်ရှင်အဖြစ် ရည်ရွယ်ခဲ့ပါသည်။",
    "Delete the student account from Settings and register again choosing \"I'm an employer\". Nothing you uploaded transfers, so do this before spending time on a profile. If certificates were already verified, they belong to the deleted account and would need uploading again.": "ဆက်တင်များမှ ကျောင်းသား အကောင့်ကို ဖျက်ပြီး ‘ကျွန်ုပ်သည် အလုပ်ရှင် ဖြစ်သည်’ ကို ရွေးကာ ပြန်လည် မှတ်ပုံတင်ပါ။ တင်ထားသည်များ လွှဲပြောင်းမရသဖြင့် ပရိုဖိုင်တွင် အချိန်မကုန်မီ ပြုလုပ်ပါ။ လက်မှတ်များ စိစစ်ပြီးဖြစ်ပါက ၎င်းတို့မှာ ဖျက်လိုက်သော အကောင့်နှင့် သက်ဆိုင်ပြီး ပြန်တင်ရပါမည်။",
    "I registered as an employer but I am a student.": "အလုပ်ရှင်အဖြစ် မှတ်ပုံတင်မိသော်လည်း ကျွန်ုပ်မှာ ကျောင်းသား ဖြစ်ပါသည်။",
    "Delete the employer account from Settings and register again as a student. The company record created with your registration is removed with the account, so an administrator is not left reviewing a company nobody owns.": "ဆက်တင်များမှ အလုပ်ရှင် အကောင့်ကို ဖျက်ပြီး ကျောင်းသားအဖြစ် ပြန်လည် မှတ်ပုံတင်ပါ။ မှတ်ပုံတင်စဉ် ဖန်တီးခဲ့သော ကုမ္ပဏီ မှတ်တမ်းလည်း အကောင့်နှင့်အတူ ဖျက်သွားမည် ဖြစ်ပြီး ပိုင်ရှင်မဲ့ ကုမ္ပဏီကို စီမံခန့်ခွဲသူ စိစစ်နေရခြင်း မဖြစ်စေပါ။",
    "A user registered under the wrong role. What do I tell them?": "အသုံးပြုသူတစ်ဦး အခန်းကဏ္ဍ မှားပြီး မှတ်ပုံတင်မိသည်။ ဘာပြောရမလဲ။",
    "That they should delete their own account from Settings and register again, which is the documented route and needs nothing from you. You can also delete it for them from the Users page. There is no way to switch a role: the profile and its records are tied to it, so switching would orphan them.": "ဆက်တင်များမှ ၎င်းတို့၏ အကောင့်ကို ကိုယ်တိုင် ဖျက်ပြီး ပြန်လည် မှတ်ပုံတင်ရန် ပြောပါ။ ၎င်းသည် စာရွက်စာတမ်းတွင် ဖော်ပြထားသော နည်းလမ်းဖြစ်ပြီး သင့်ထံမှ ဘာမျှ မလိုအပ်ပါ။ အသုံးပြုသူများ စာမျက်နှာမှလည်း သင် ဖျက်ပေးနိုင်ပါသည်။ အခန်းကဏ္ဍ ပြောင်းရန် နည်းလမ်း မရှိပါ — ပရိုဖိုင်နှင့် မှတ်တမ်းများ ၎င်းနှင့် ချိတ်ဆက်နေသောကြောင့် ပြောင်းလျှင် ပိုင်ရှင်မဲ့ ဖြစ်သွားပါမည်။",

    "Forgot your password?": "စကားဝှက် မေ့နေပါသလား။",
    "Enter your email and we will send a code.": "သင့် အီးမေးလ် ထည့်ပါ။ ကုဒ်တစ်ခု ပို့ပေးပါမည်။",
    "Enter the code from the email and choose a new password.": "အီးမေးလ်ထဲမှ ကုဒ်ကို ထည့်ပြီး စကားဝှက် အသစ် ရွေးပါ။",
    "Code from the email": "အီးမေးလ်မှ ကုဒ်",
    "Send me a code": "ကုဒ် ပို့ပေးပါ",
    "Send another code": "ကုဒ် ထပ်ပို့ပါ",
    "Change my password": "စကားဝှက် ပြောင်းရန်",
    "Password changed": "စကားဝှက် ပြောင်းပြီးပါပြီ",
    "You can sign in with your new password now.": "စကားဝှက် အသစ်ဖြင့် ယခု ဝင်ရောက်နိုင်ပါပြီ။",
    "Back to sign in": "ဝင်ရောက်ရန် စာမျက်နှာသို့ ပြန်သွားရန်",
    "Please wait...": "ခဏစောင့်ပါ...",

    "LinkedIn": "LinkedIn",

    "{shown} of {total} shown": "{total} ခုအနက် {shown} ခု ပြသထားသည်",
    "Clear search": "ရှာဖွေမှု ရှင်းရန်",
    "Search companies": "ကုမ္ပဏီများ ရှာရန်",
    "Search certificates": "လက်မှတ်များ ရှာရန်",
    "Search internships": "အလုပ်သင်နေရာများ ရှာရန်",
    "Search applications": "လျှောက်လွှာများ ရှာရန်",
    "Search feedback": "အကြံပြုချက်များ ရှာရန်",

    "Business registration number": "လုပ်ငန်း မှတ်ပုံတင် အမှတ်",
    "An administrator checks this before approving you.": "အတည်မပြုမီ စီမံခန့်ခွဲသူက ဤအချက်ကို စစ်ဆေးပါသည်။",
    "Company contact email": "ကုမ္ပဏီ ဆက်သွယ်ရန် အီးမေးလ်",
    "What the company does": "ကုမ္ပဏီ၏ လုပ်ငန်းအကြောင်း",
    "Students read this before deciding whether to apply.": "လျှောက်ရန် ဆုံးဖြတ်မီ ကျောင်းသားများ ဤအချက်ကို ဖတ်ကြပါသည်။",

    "View details": "အသေးစိတ် ကြည့်ရန်",
    "Feedback": "အကြံပြုချက်",
    "Someone": "တစ်စုံတစ်ဦး",
    "There is no reply channel. Contact them directly if you need to follow up.": "ပြန်ကြားရန် လမ်းကြောင်း မရှိပါ။ ဆက်လက် ဆောင်ရွက်လိုပါက ၎င်းတို့ကို တိုက်ရိုက် ဆက်သွယ်ပါ။",

    "The chat does. The calculated features - skill matching, what to learn next, the company review, the administrator workload - are worked out from the database in plain code, so they keep working with no API key and no connection.": "စကားပြောခြင်းအတွက် လိုအပ်ပါသည်။ တွက်ချက်မှုဆိုင်ရာ လုပ်ဆောင်ချက်များ — ကျွမ်းကျင်မှု တွဲပေးခြင်း၊ နောက်တစ်ဆင့် ဘာသင်ရမည်၊ ကုမ္ပဏီ သုံးသပ်ချက်၊ စီမံခန့်ခွဲသူ၏ အလုပ်ပမာဏ — တို့ကို ဒေတာဘေ့စ်မှ ရိုးရိုးကုဒ်ဖြင့် တွက်ချက်သဖြင့် API key မရှိဘဲ၊ အင်တာနက် မရှိဘဲ ဆက်လက် အလုပ်လုပ်ပါသည်။",
    "The EN / မြန်မာ toggle at the top right, available before you sign in as well as after. The assistant follows it too, so questions asked with Burmese selected are answered in Burmese.": "အပေါ်ညာဘက်ရှိ EN / မြန်မာ ခလုတ်ဖြင့် ပြောင်းနိုင်ပါသည်။ ဝင်ရောက်မီရော ဝင်ရောက်ပြီးနောက်ပါ အသုံးပြုနိုင်သည်။ အကူအညီကလည်း ၎င်းကို လိုက်နာသဖြင့် မြန်မာဘာသာ ရွေးထားစဉ် မေးသော မေးခွန်းများကို မြန်မာလို ဖြေပါသည်။",
    "Your profile is visible to an employer only when you apply to their vacancy. Certificates are visible only after an administrator has verified them. Nothing is shared with anyone you have not applied to.": "သင့်ပရိုဖိုင်ကို သင် လျှောက်ထားသော နေရာ၏ အလုပ်ရှင်သာ မြင်ရပါသည်။ လက်မှတ်များကို စီမံခန့်ခွဲသူ စိစစ်ပြီးမှသာ မြင်ရပါသည်။ သင် မလျှောက်ထားသူ မည်သူ့ကိုမျှ မျှဝေခြင်း မရှိပါ။",

    // --- FAQ questions and answers ---------------------------------------
    "Is the AI assistant deciding anything?": "AI အကူအညီသည် တစ်စုံတစ်ရာ ဆုံးဖြတ်ပါသလား။",
    "No. It reads data you already have access to and offers advice. It cannot accept or reject an application, verify a certificate, approve a company, or change any record. Every decision on this platform is made by a person.": "မဆုံးဖြတ်ပါ။ သင် ကြည့်ခွင့်ရှိပြီးသား အချက်အလက်များကို ဖတ်ပြီး အကြံပြုရုံသာ ဖြစ်သည်။ လျှောက်လွှာ လက်ခံခြင်း၊ ငြင်းပယ်ခြင်း၊ လက်မှတ် စိစစ်ခြင်း၊ ကုမ္ပဏီ အတည်ပြုခြင်း သို့မဟုတ် မှတ်တမ်း ပြောင်းလဲခြင်း မပြုနိုင်ပါ။ ဤစနစ်ရှိ ဆုံးဖြတ်ချက်တိုင်းကို လူက ချမှတ်ပါသည်။",
    "Why is some of the interface still in English?": "အဘယ်ကြောင့် အချို့နေရာများ အင်္ဂလိပ်လို ကျန်နေသနည်း။",
    "Anything a person typed - a certificate title, a company name, a cover letter - is shown exactly as written, because translating someone's own words would misrepresent them. Product names such as MariaDB and technical terms that Myanmar workplaces use in English are also left alone.": "လူတစ်ဦး ရိုက်ထည့်ခဲ့သည့် အရာများ — လက်မှတ် ခေါင်းစဉ်၊ ကုမ္ပဏီ အမည်၊ လျှောက်လွှာစာ — ကို ရေးထားသည့်အတိုင်း ပြသပါသည်။ သူတို့၏ စကားလုံးများကို ဘာသာပြန်ပါက အဓိပ္ပာယ် လွဲမှားစေနိုင်သောကြောင့် ဖြစ်သည်။ MariaDB ကဲ့သို့ ထုတ်ကုန်အမည်များနှင့် မြန်မာ့ လုပ်ငန်းခွင်တွင် အင်္ဂလိပ်လို သုံးလေ့ရှိသော နည်းပညာ ဝေါဟာရများကိုလည်း ထားရှိပါသည်။",
    "How do I change my password?": "စကားဝှက်ကို မည်သို့ ပြောင်းရမလဲ။",
    "Settings, under Account. You need your current password, which is why someone who finds your computer unlocked still cannot lock you out of your own account.": "ဆက်တင်များ ထဲရှိ အကောင့် အောက်တွင် ရှိပါသည်။ လက်ရှိ စကားဝှက် လိုအပ်ပါသည်။ ထို့ကြောင့် သင့်ကွန်ပျူတာကို ဖွင့်ထားသည်ကို တွေ့သူပင် သင့်အကောင့်မှ သင့်ကို ပိတ်ထုတ်၍ မရပါ။",
    "Why can't employers see my certificate?": "အလုပ်ရှင်များ ကျွန်ုပ်၏ လက်မှတ်ကို အဘယ်ကြောင့် မမြင်ရသနည်း။",
    "Only verified certificates are ever sent to employers. After you upload one it waits for an administrator to open the file and check it against the qualification it claims. That check is the whole point of the platform.": "စိစစ်ပြီးသော လက်မှတ်များကိုသာ အလုပ်ရှင်များထံ ပို့ပါသည်။ တင်ပြီးနောက် စီမံခန့်ခွဲသူက ဖိုင်ကို ဖွင့်၍ ဖော်ပြထားသော အရည်အချင်းနှင့် ကိုက်ညီမှု ရှိမရှိ စစ်ဆေးသည်အထိ စောင့်ဆိုင်းရပါသည်။ ထိုစစ်ဆေးမှုသည်ပင် ဤစနစ်၏ အဓိက ရည်ရွယ်ချက် ဖြစ်သည်။",
    "My certificate was rejected. What now?": "ကျွန်ုပ်၏ လက်မှတ် ငြင်းပယ်ခံရသည်။ ဘာဆက်လုပ်ရမလဲ။",
    "The rejection comes with a note explaining why. Fix what it describes and upload again - there is no limit on attempts.": "ငြင်းပယ်ချက်တွင် အကြောင်းရင်း ရှင်းပြထားသော မှတ်ချက် ပါလာပါသည်။ ဖော်ပြထားသည်ကို ပြင်ဆင်ပြီး ပြန်တင်ပါ — ကြိုးစားနိုင်သည့် အကြိမ်အရေအတွက် ကန့်သတ်ချက် မရှိပါ။",
    "How are internships matched to me?": "အလုပ်သင်နေရာများကို ကျွန်ုပ်နှင့် မည်သို့ တွဲပေးသနည်း။",
    "Each vacancy lists required skills. Your profile is scored against that list and the score is explained, so you can see exactly which skill made the difference rather than trusting a number.": "နေရာတိုင်းတွင် လိုအပ်သော ကျွမ်းကျင်မှုများ ဖော်ပြထားပါသည်။ သင့်ပရိုဖိုင်ကို ထိုစာရင်းနှင့် နှိုင်းယှဉ် အမှတ်ပေးပြီး အဘယ်ကြောင့်ဖြစ်ကြောင်း ရှင်းပြပါသည်။ ထို့ကြောင့် ကိန်းဂဏန်းကို ယုံရုံမျှမက မည်သည့် ကျွမ်းကျင်မှုက ကွာခြားစေသည်ကို မြင်ရပါမည်။",
    "I applied but nothing has happened.": "လျှောက်ထားပြီးဖြစ်သော်လည်း ဘာမှ မဖြစ်သေးပါ။",
    "Employers review applications themselves, and the platform cannot make them faster. Your status changes as soon as they act, and you are notified when it does. An administrator can see applications no employer has opened for over seven days.": "အလုပ်ရှင်များက လျှောက်လွှာများကို ကိုယ်တိုင် စိစစ်ကြပြီး စနစ်က ၎င်းတို့ကို မြန်စေအောင် မလုပ်နိုင်ပါ။ ၎င်းတို့ လုပ်ဆောင်သည်နှင့် သင့်အခြေအနေ ပြောင်းလဲပြီး သင့်ကို အသိပေးပါမည်။ ခုနစ်ရက်ကျော် အလုပ်ရှင် မဖွင့်ရသေးသော လျှောက်လွှာများကို စီမံခန့်ခွဲသူက မြင်နိုင်ပါသည်။",
    "An employer asked me for more information. How do I reply?": "အလုပ်ရှင်တစ်ဦးက အချက်အလက် ထပ်တောင်းသည်။ မည်သို့ ပြန်ဖြေရမလဲ။",
    "Not through the platform - the request is one-way by design. Contact them using the details on the internship listing, or attach what they asked for to your profile so it is there next time.": "ဤစနစ်မှတစ်ဆင့် မဟုတ်ပါ — တောင်းဆိုချက်မှာ တစ်လမ်းသွားသာ ဖြစ်ရန် ရည်ရွယ်ထားသည်။ အလုပ်သင်နေရာ ကြေညာချက်ရှိ ဆက်သွယ်ရန် အချက်အလက်များဖြင့် ဆက်သွယ်ပါ၊ သို့မဟုတ် တောင်းဆိုသည်များကို သင့်ပရိုဖိုင်တွင် ထည့်ထားပါ။",
    "What does the profile completeness percentage mean?": "ပရိုဖိုင် ပြည့်စုံမှု ရာခိုင်နှုန်းက ဘာကို ဆိုလိုသနည်း။",
    "How much of your profile an employer would actually see: your details, education, skills and at least one verified certificate. It is a prompt, not a score anyone judges you against.": "အလုပ်ရှင်တစ်ဦး အမှန်တကယ် မြင်ရမည့် သင့်ပရိုဖိုင်၏ အချိုးအစား — သင့်အချက်အလက်၊ ပညာရေး၊ ကျွမ်းကျင်မှုများနှင့် အနည်းဆုံး စိစစ်ပြီး လက်မှတ် တစ်ခု။ ၎င်းသည် သတိပေးချက်သာ ဖြစ်ပြီး မည်သူကမျှ အဲဒါနဲ့ သင့်ကို အဆင့်သတ်မှတ်ခြင်း မဟုတ်ပါ။",
    "Why can't I publish an internship?": "အလုပ်သင်နေရာကို အဘယ်ကြောင့် မကြေညာနိုင်သနည်း။",
    "Vacancies stay as drafts until an administrator approves your company. Until then no student can see them. You are emailed and notified the moment that happens.": "စီမံခန့်ခွဲသူက သင့်ကုမ္ပဏီကို အတည်မပြုမချင်း နေရာများမှာ မူကြမ်း အဆင့်တွင်သာ ရှိနေပါမည်။ ထိုအချိန်အထိ ကျောင်းသားများ မမြင်ရပါ။ အတည်ပြုသည်နှင့် သင့်ထံ အီးမေးလ်နှင့် အသိပေးချက် ပို့ပါမည်။",
    "Nobody is applying to my vacancy. Why?": "ကျွန်ုပ်၏ နေရာသို့ မည်သူမျှ မလျှောက်ကြပါ။ အဘယ်ကြောင့်နည်း။",
    "Ask the assistant - the My company tab lists what each listing is missing. The usual causes are no required skills, so students cannot be matched to it, and no stipend information.": "အကူအညီကို မေးပါ — ကျွန်ုပ်၏ ကုမ္ပဏီ တက်ဘ်တွင် ကြေညာချက်တစ်ခုစီ၌ လိုအပ်နေသည်များကို ဖော်ပြပါသည်။ အဖြစ်များသည့် အကြောင်းရင်းများမှာ လိုအပ်သော ကျွမ်းကျင်မှု မသတ်မှတ်ထားခြင်း — ထို့ကြောင့် ကျောင်းသားများနှင့် တွဲပေး၍ မရခြင်း — နှင့် ထောက်ပံ့ကြေး အချက်အလက် မရှိခြင်း ဖြစ်သည်။",
    "Can I message an applicant?": "လျှောက်ထားသူထံ စာပို့နိုင်ပါသလား။",
    "You can send one request for more information, which arrives in their notifications. It is one-way: they cannot reply through the platform, so ask for something they can act on.": "အချက်အလက် ထပ်တောင်းသည့် တောင်းဆိုချက် တစ်ခု ပို့နိုင်ပြီး ၎င်းတို့၏ အသိပေးချက်များထဲ ရောက်ပါမည်။ တစ်လမ်းသွား ဖြစ်သည် — ၎င်းတို့ ဤစနစ်မှတစ်ဆင့် ပြန်မဖြေနိုင်သဖြင့် လုပ်ဆောင်နိုင်သည့် အရာကို တောင်းပါ။",
    "Are the certificates I see real?": "ကျွန်ုပ် မြင်ရသော လက်မှတ်များ အစစ်ဖြစ်ပါသလား။",
    "Every certificate on an applicant's profile has been opened and checked by an administrator against the qualification it claims. Unverified ones are never sent to you, which is the main thing this platform offers over a CV.": "လျှောက်ထားသူ၏ ပရိုဖိုင်ရှိ လက်မှတ်တိုင်းကို စီမံခန့်ခွဲသူက ဖွင့်၍ ဖော်ပြထားသော အရည်အချင်းနှင့် ကိုက်ညီမှု စစ်ဆေးပြီး ဖြစ်သည်။ မစိစစ်ရသေးသည်များကို သင့်ထံ လုံးဝ မပို့ပါ။ ၎င်းသည် CV တစ်ခုထက် ဤစနစ်၏ အဓိက သာလွန်ချက် ဖြစ်သည်။",
    "Why does the assistant say a skill is hard to fill?": "ကျွမ်းကျင်မှုတစ်ခုကို ရှာရခက်သည်ဟု အကူအညီက အဘယ်ကြောင့် ဆိုသနည်း။",
    "Because it counted how many students on the platform list it. If almost none do, requiring it will keep the vacancy empty - consider marking it nice-to-have, or accepting a related skill.": "စနစ်ပေါ်ရှိ ကျောင်းသား မည်မျှက ၎င်းကို ဖော်ပြထားသည်ကို ရေတွက်ထားသောကြောင့် ဖြစ်သည်။ အနည်းငယ်မျှသာ ရှိပါက မဖြစ်မနေ လိုအပ်သည်အဖြစ် ထားခြင်းက နေရာကို လွတ်နေစေပါမည် — ရှိလျှင်ကောင်းသည်အဖြစ် ပြောင်းရန် သို့မဟုတ် ဆက်စပ် ကျွမ်းကျင်မှု လက်ခံရန် စဉ်းစားပါ။",
    "Can I edit a vacancy after publishing it?": "ကြေညာပြီးနောက် နေရာကို ပြင်ဆင်နိုင်ပါသလား။",
    "Yes, from Manage internships. Applications already received are kept.": "ရပါသည်။ အလုပ်သင်နေရာများ စီမံရန် မှတစ်ဆင့် ပြင်နိုင်သည်။ လက်ခံရရှိပြီးသော လျှောက်လွှာများ ကျန်ရှိနေပါမည်။",
    "What happens when I verify a certificate?": "လက်မှတ်တစ်ခု စိစစ်လိုက်လျှင် ဘာဖြစ်သွားသနည်း။",
    "It becomes visible to every employer who receives an application from that student. Nothing else in the system can make that happen, which is why the queue matters.": "ထိုကျောင်းသားထံမှ လျှောက်လွှာ လက်ခံရရှိသော အလုပ်ရှင်တိုင်း မြင်နိုင်လာပါမည်။ စနစ်ထဲရှိ အခြားမည်သည့်အရာကမျှ ထိုသို့ မလုပ်နိုင်ပါ။ ထို့ကြောင့် စောင့်ဆိုင်းစာရင်းသည် အရေးကြီးပါသည်။",
    "What does approving a company do?": "ကုမ္ပဏီတစ်ခု အတည်ပြုလိုက်လျှင် ဘာဖြစ်သနည်း။",
    "It activates the recruiter accounts attached to it and lets their vacancies be published. They are emailed and notified.": "၎င်းနှင့် ချိတ်ဆက်ထားသော အလုပ်ခေါ်ယူသူ အကောင့်များကို အသက်သွင်းပြီး ၎င်းတို့၏ နေရာများကို ကြေညာခွင့် ပေးပါသည်။ ၎င်းတို့ထံ အီးမေးလ်နှင့် အသိပေးချက် ပို့ပါသည်။",
    "Should I suspend or delete an account?": "အကောင့်ကို ရပ်ဆိုင်းသင့်သလား၊ ဖျက်သင့်သလား။",
    "Suspend, almost always. It is reversible and keeps the person's history. Deleting is permanent and removes their applications and certificates - it is for duplicates and test accounts.": "အမြဲလိုလို ရပ်ဆိုင်းသင့်ပါသည်။ ပြန်ပြင်နိုင်ပြီး ထိုသူ၏ မှတ်တမ်းများ ကျန်ရှိပါသည်။ ဖျက်ခြင်းမှာ အပြီးအပိုင်ဖြစ်ပြီး ၎င်းတို့၏ လျှောက်လွှာများနှင့် လက်မှတ်များပါ ပျောက်သွားပါမည် — ထပ်နေသော အကောင့်များနှင့် စမ်းသပ် အကောင့်များအတွက်သာ ဖြစ်သည်။",
    "What does 'stalled' mean on the dashboard?": "ဒက်ရှ်ဘုတ်ရှိ ‘ရပ်တန့်နေသည်’ ဆိုသည်မှာ ဘာကို ဆိုလိုသနည်း။",
    "An application no employer has opened for over seven days. You cannot decide it for them, but you can see who is holding someone up.": "ခုနစ်ရက်ကျော်ကြာ အလုပ်ရှင် မဖွင့်ရသေးသော လျှောက်လွှာ ဖြစ်သည်။ ၎င်းတို့ကိုယ်စား သင် ဆုံးဖြတ်၍ မရသော်လည်း မည်သူက တစ်စုံတစ်ဦးကို နှောင့်နှေးစေနေသည်ကို မြင်နိုင်ပါသည်။",
    "Can the assistant approve anything for me?": "အကူအညီက ကျွန်ုပ်ကိုယ်စား တစ်စုံတစ်ရာ အတည်ပြုပေးနိုင်ပါသလား။",
    "No. It can tell you what is waiting and what is most urgent, and it can explain why. Every approval, rejection and verification is yours.": "မရပါ။ ဘာတွေ စောင့်ဆိုင်းနေသည်၊ ဘာက အရေးအကြီးဆုံးဖြစ်သည်ကို ပြောပြနိုင်ပြီး အကြောင်းရင်းကိုလည်း ရှင်းပြနိုင်ပါသည်။ အတည်ပြုခြင်း၊ ငြင်းပယ်ခြင်းနှင့် စိစစ်ခြင်းတိုင်းမှာ သင့်တာဝန် ဖြစ်သည်။",
    "Where does user feedback arrive?": "အသုံးပြုသူများ၏ အကြံပြုချက်များ ဘယ်ကို ရောက်သနည်း။",
    "As a notification to every administrator, including this one. It is delivered rather than stored, so it cannot yet be marked resolved or replied to.": "ဤအကောင့်အပါအဝင် စီမံခန့်ခွဲသူတိုင်းထံ အသိပေးချက်အဖြစ် ရောက်ပါသည်။ သိမ်းဆည်းခြင်းမဟုတ်ဘဲ ပို့ဆောင်ခြင်းသာ ဖြစ်သဖြင့် ဖြေရှင်းပြီးအဖြစ် မှတ်ခြင်း သို့မဟုတ် ပြန်ကြားခြင်း မပြုနိုင်သေးပါ။",

    "Administrator accounts cannot be changed from this screen.": "စီမံခန့်ခွဲသူ အကောင့်များကို ဤစာမျက်နှာမှ ပြောင်းလဲ၍ မရပါ။",

    "Feedback from users": "အသုံးပြုသူများ၏ အကြံပြုချက်များ",
    "No feedback yet": "အကြံပြုချက် မရှိသေးပါ",
    "Messages sent from the FAQ page on the student and employer sites arrive here.": "ကျောင်းသားနှင့် အလုပ်ရှင် စာမျက်နှာများရှိ FAQ မှ ပို့သော စာများ ဤနေရာသို့ ရောက်ပါသည်။",
    "Loading feedback...": "အကြံပြုချက်များ ရယူနေသည်...",
    "Feedback is delivered as a notification rather than stored as its own record, so it cannot yet be marked resolved or replied to.": "အကြံပြုချက်များကို သီးခြား မှတ်တမ်းအဖြစ် မသိမ်းဘဲ အသိပေးချက်အဖြစ် ပို့ဆောင်သောကြောင့် ဖြေရှင်းပြီးအဖြစ် မှတ်ခြင်း သို့မဟုတ် ပြန်ကြားခြင်း မပြုနိုင်သေးပါ။",
    "Person": "ပုဂ္ဂိုလ်",
    "Never": "မရှိပါ",

    "At a glance": "အနှစ်ချုပ်",
    "The same figures above, shaped so the differences are visible.": "အထက်ပါ ကိန်းဂဏန်းများကို ကွာခြားချက် မြင်သာအောင် ပြသထားခြင်း။",
    "Accounts by role": "အခန်းကဏ္ဍအလိုက် အကောင့်များ",
    "Waiting for a decision": "ဆုံးဖြတ်ချက် စောင့်ဆိုင်းနေသည်များ",
    "A bar at zero is the target. Anything else is someone waiting.": "သုညဖြစ်ခြင်းသည် ပန်းတိုင် ဖြစ်သည်။ ကျန်သည်များမှာ တစ်စုံတစ်ဦး စောင့်ဆိုင်းနေခြင်း ဖြစ်သည်။",
    "AI calls": "AI ခေါ်ဆိုမှုများ",
    "No calls recorded yet.": "မှတ်တမ်းတင်ထားသော ခေါ်ဆိုမှု မရှိသေးပါ။",
    "Failures are usually a provider limit or a missing key, not a fault in the platform.": "မအောင်မြင်မှုများသည် များသောအားဖြင့် ဝန်ဆောင်မှုပေးသူ၏ ကန့်သတ်ချက် သို့မဟုတ် key မရှိခြင်းကြောင့် ဖြစ်ပြီး စနစ်၏ ချွတ်ယွင်းချက် မဟုတ်ပါ။",
    "No data yet.": "အချက်အလက် မရှိသေးပါ။",
    "Account details": "အကောင့် အချက်အလက်",
    "Unnamed account": "အမည် မရှိသော အကောင့်",
    "Account ID": "အကောင့် အမှတ်",
    "Actions": "လုပ်ဆောင်ချက်များ",
    "Suspend account": "အကောင့် ရပ်ဆိုင်းရန်",
    "Reactivate account": "အကောင့် ပြန်ဖွင့်ရန်",
    "Delete account": "အကောင့် ဖျက်ရန်",
    "Suspending is reversible and keeps the person's records. Deleting is permanent.": "ရပ်ဆိုင်းခြင်းသည် ပြန်ပြင်နိုင်ပြီး မှတ်တမ်းများ ကျန်ရှိပါသည်။ ဖျက်ခြင်းမှာ အပြီးအပိုင် ဖြစ်သည်။",
    "A role cannot be changed after registration: the profile and its records are tied to it. Delete the account and register again instead.": "မှတ်ပုံတင်ပြီးနောက် အခန်းကဏ္ဍ ပြောင်း၍ မရပါ — ပရိုဖိုင်နှင့် မှတ်တမ်းများ ၎င်းနှင့် ချိတ်ဆက်နေပါသည်။ အကောင့်ကို ဖျက်ပြီး ပြန်လည် မှတ်ပုံတင်ပါ။",
    "No description": "ဖော်ပြချက် မရှိပါ",
    "STUDENT": "ကျောင်းသား",

    "{n} questions": "မေးခွန်း {n} ခု",
    "Does the assistant need an internet connection?": "အကူအညီအတွက် အင်တာနက် လိုအပ်ပါသလား။",
    "How do I switch between English and Burmese?": "အင်္ဂလိပ်နှင့် မြန်မာ ဘာသာ မည်သို့ ပြောင်းရမလဲ။",
    "Is my data shared with anyone?": "ကျွန်ုပ်၏ အချက်အလက်များကို မည်သူ့ကိုမဆို မျှဝေပါသလား။",

    // --- help and FAQ ------------------------------------------------------
    "nav.faq": "အကူအညီနှင့် မေးခွန်းများ",
    "Help and FAQ": "အကူအညီနှင့် မေးလေ့ရှိသော မေးခွန်းများ",
    "Common questions, and a way to ask something we have not answered.": "မေးလေ့ရှိသော မေးခွန်းများနှင့် မဖြေရသေးသည်များ မေးရန် နည်းလမ်း။",
    "Frequently asked questions": "မေးလေ့ရှိသော မေးခွန်းများ",
    "Leave feedback": "အကြံပြုချက် ပေးရန်",
    "This goes to the administrators as a notification. Tell us what is confusing, broken, or missing.": "ဤအရာသည် စီမံခန့်ခွဲသူများထံ အသိပေးချက်အဖြစ် ရောက်ပါမည်။ ရှုပ်ထွေးသည်များ၊ ချွတ်ယွင်းသည်များ သို့မဟုတ် လိုအပ်သည်များကို ပြောပြပါ။",
    "What would you change?": "ဘာကို ပြောင်းလဲစေချင်ပါသလဲ။",
    "Send feedback": "အကြံပြုချက် ပို့ရန်",
    "Sending...": "ပို့နေသည်...",
    "Ask our AI for more questions": "နောက်ထပ် မေးခွန်းများအတွက် ကျွန်ုပ်တို့၏ AI ကို မေးပါ",
    "Hide": "ဖျောက်ရန်",

    "Note from the administrator": "စီမံခန့်ခွဲသူ၏ မှတ်ချက်",

    "Programming languages": "ပရိုဂရမ်းမင်း ဘာသာစကားများ",
    "Technical": "နည်းပညာဆိုင်ရာ",
    "Soft skills": "လူမှုကျွမ်းကျင်မှုများ",
    "Languages": "ဘာသာစကားများ",
    "Skill name": "ကျွမ်းကျင်မှု အမည်",
    "Skill type": "ကျွမ်းကျင်မှု အမျိုးအစား",
    "Add a skill": "ကျွမ်းကျင်မှု ထည့်ရန်",
    "Edit skill": "ကျွမ်းကျင်မှု ပြင်ဆင်ရန်",
    "Edit": "ပြင်ဆင်ရန်",
    "Back to My Profile": "ပရိုဖိုင်သို့ ပြန်သွားရန်",
    "No skills yet. They are what the assistant matches you to vacancies with.": "ကျွမ်းကျင်မှု မရှိသေးပါ။ ၎င်းတို့ဖြင့် အကူအညီက သင့်ကို နေရာများနှင့် တွဲပေးပါသည်။",

    // --- employer pages ----------------------------------------------------
    "Here is what is happening with your hiring today.": "ယနေ့ သင်၏ ဝန်ထမ်းခေါ်ယူမှု အခြေအနေ။",
    "Create a vacancy and publish it once your company is approved.": "အလုပ်နေရာ ဖန်တီးပြီး ကုမ္ပဏီ အတည်ပြုပြီးသည်နှင့် ကြေညာပါ။",
    "Review applicants": "လျှောက်ထားသူများ စိစစ်ရန်",
    "Shortlist, accept or reject the people who applied.": "လျှောက်ထားသူများကို ရွေးချယ်ရန်၊ လက်ခံရန် သို့မဟုတ် ငြင်းပယ်ရန်။",
    "Compare candidates, or find out why nobody is applying.": "လျှောက်ထားသူများ နှိုင်းယှဉ်ရန်၊ သို့မဟုတ် အဘယ်ကြောင့် မလျှောက်ကြသည်ကို သိရန်။",
    "Share of applicants accepted": "လက်ခံခဲ့သော လျှောက်ထားသူ အချိုး",
    "Skills you require that students rarely have": "ကျောင်းသားများ ရှားပါးစွာ ရှိသော သင်တောင်းဆိုသည့် ကျွမ်းကျင်မှုများ",
    "{n} student(s)": "ကျောင်းသား {n} ဦး",
    "Open": "ဖွင့်ထားသည်",
    "Drafts": "မူကြမ်းများ",
    "Applicants": "လျှောက်ထားသူများ",
    "Unreviewed": "မစိစစ်ရသေး",
    "Suggested fixes": "အကြံပြု ပြင်ဆင်ချက်များ",
    "Your company is approved. You can publish internships.": "သင့်ကုမ္ပဏီ အတည်ပြုပြီး ဖြစ်ပါသည်။ အလုပ်သင်နေရာများ ကြေညာနိုင်ပါပြီ။",
    "Until an administrator approves your company, your internships stay as drafts and no student can see them.": "စီမံခန့်ခွဲသူ အတည်မပြုမချင်း သင့် အလုပ်သင်နေရာများမှာ မူကြမ်းအဆင့်တွင်သာ ရှိပြီး ကျောင်းသားများ မမြင်ရပါ။",
    "Approval status": "အတည်ပြုချက် အခြေအနေ",

    // post an internship
    "Title": "ခေါင်းစဉ်",
    "Duration (months)": "ကြာချိန် (လ)",
    "Stipend amount": "ထောက်ပံ့ကြေး ပမာဏ",
    "Stipend currency": "ငွေကြေး အမျိုးအစား",
    "Available positions": "လက်ခံမည့် နေရာ အရေအတွက်",
    "Application deadline": "လျှောက်လွှာ ပိတ်ရက်",
    "No deadline": "ပိတ်ရက် မရှိ",
    "On-site": "ရုံးတွင်",
    "Remote": "အဝေးမှ",
    "Hybrid": "ရောနှော",
    "Draft - only you can see it": "မူကြမ်း — သင်သာ မြင်ရသည်",
    "Open - visible to students once approved": "ဖွင့်ထားသည် — အတည်ပြုပြီးလျှင် ကျောင်းသားများ မြင်ရမည်",
    "Save draft": "မူကြမ်း သိမ်းရန်",
    "Publish internship": "အလုပ်သင်နေရာ ကြေညာရန်",

    // company profile
    "Company size": "ကုမ္ပဏီ အရွယ်အစား",
    "Founded year": "တည်ထောင်သည့်နှစ်",
    "What an administrator checks before approving you.": "အတည်မပြုမီ စီမံခန့်ခွဲသူ စစ်ဆေးသည့် အချက်။",
    "Address": "လိပ်စာ",
    "Website": "ဝဘ်ဆိုက်",
    "Contact email": "ဆက်သွယ်ရန် အီးမေးလ်",
    "Company description": "ကုမ္ပဏီ ဖော်ပြချက်",

    // --- student pages -----------------------------------------------------
    "Welcome back": "ပြန်လည် ကြိုဆိုပါသည်",
    "Here is where your internship search stands.": "သင်၏ အလုပ်သင်နေရာ ရှာဖွေမှု အခြေအနေ။",
    "Quick actions": "အမြန် လုပ်ဆောင်ချက်များ",
    "Nothing missing": "လိုအပ်သည် မရှိပါ",
    "{n} thing(s) missing": "{n} ခု လိုအပ်နေပါသည်",
    "The skill most worth learning next is {skill}, asked for by {n} of the {total} open internships.": "နောက်တစ်ဆင့် သင်ယူရန် အသုံးဝင်ဆုံးမှာ {skill} ဖြစ်ပြီး ဖွင့်ထားသော နေရာ {total} ခုအနက် {n} ခုက တောင်းဆိုပါသည်။",
    "Find open vacancies and apply.": "ဖွင့်ထားသော နေရာများ ရှာပြီး လျှောက်ထားပါ။",
    "Employers only see qualifications an administrator has verified.": "စီမံခန့်ခွဲသူ စိစစ်ပြီးသော အရည်အချင်းများကိုသာ အလုပ်ရှင်များ မြင်ရပါသည်။",
    "Ask the assistant": "အကူအညီကို မေးရန်",
    "What to learn next, and which vacancies fit.": "နောက်တစ်ဆင့် ဘာသင်ရမည်နှင့် မည်သည့်နေရာများ ကိုက်ညီသည်။",

    // certificates
    "Certificate name": "လက်မှတ် အမည်",
    "Certificate file": "လက်မှတ် ဖိုင်",
    "Choose file": "ဖိုင် ရွေးရန်",
    "No file chosen": "ဖိုင် မရွေးရသေးပါ",
    "PDF, PNG or JPG.": "PDF, PNG သို့မဟုတ် JPG။",
    "Upload certificate": "လက်မှတ် တင်ရန်",
    "{n} certificate(s) are waiting to be reviewed. Until then they are not visible to employers.": "လက်မှတ် {n} ခု စိစစ်ရန် စောင့်ဆိုင်းနေပါသည်။ ထိုအချိန်အထိ အလုပ်ရှင်များ မမြင်ရပါ။",
    "A rejected certificate comes back with a note explaining why, so you can correct it and upload again.": "ငြင်းပယ်ခံရသော လက်မှတ်တွင် အကြောင်းပြချက် ပါလာမည်ဖြစ်၍ ပြင်ဆင်ပြီး ပြန်တင်နိုင်ပါသည်။",

    // what to learn
    "Most requested skills you don't have yet": "သင့်တွင် မရှိသေးသော အတောင်းဆိုဆုံး ကျွမ်းကျင်မှုများ",
    "required by {n} of {total} open internships": "ဖွင့်ထားသော နေရာ {total} ခုအနက် {n} ခုက တောင်းဆိုသည်",
    "Not currently requested by any open internship: {list}. Keep them - this only reflects the vacancies on the platform right now.": "ယခုအချိန်တွင် မည်သည့် ဖွင့်ထားသော နေရာကမျှ မတောင်းဆိုသေးပါ— {list}။ ဆက်ထားပါ — ဤသည်မှာ လက်ရှိ စနစ်ပေါ်ရှိ နေရာများကိုသာ ထင်ဟပ်ပါသည်။",
    "The assistant gives advice only. It cannot accept or reject anyone, change an application, or see unverified certificates.": "အကူအညီသည် အကြံပြုချက်သာ ပေးပါသည်။ မည်သူ့ကိုမျှ လက်ခံခြင်း၊ ငြင်းပယ်ခြင်း၊ လျှောက်လွှာ ပြောင်းလဲခြင်း သို့မဟုတ် မစိစစ်ရသေးသော လက်မှတ်များ ကြည့်ခြင်း မပြုနိုင်ပါ။",

    // --- the panel beside the sign-in form ---------------------------------
    "Find opportunities. Build your future.": "အခွင့်အလမ်းများ ရှာပါ။ သင့်အနာဂတ်ကို တည်ဆောက်ပါ။",
    "Matched on real skills": "အမှန်တကယ် ကျွမ်းကျင်မှုအလိုက် တွဲပေးခြင်း",
    "Every internship is scored against what you can actually do, and the score explains itself.": "အလုပ်သင်နေရာတိုင်းကို သင် အမှန်တကယ် လုပ်နိုင်သည်များနှင့် နှိုင်းယှဉ် အမှတ်ပေးပြီး အဘယ်ကြောင့်ဖြစ်ကြောင်း ရှင်းပြပါသည်။",
    "Verified qualifications": "စိစစ်ပြီး အရည်အချင်းများ",
    "Employers only ever see certificates an administrator has checked.": "စီမံခန့်ခွဲသူ စိစစ်ပြီးသော လက်မှတ်များကိုသာ အလုပ်ရှင်များ မြင်ရပါသည်။",
    "Guidance that reads your profile": "သင့်ပရိုဖိုင်ကို ဖတ်ပြီး လမ်းညွှန်ခြင်း",
    "The assistant works from your own data - what to learn next, and what is missing.": "အကူအညီသည် သင့်ကိုယ်ပိုင် အချက်အလက်များမှ လုပ်ဆောင်ပါသည် — နောက်တစ်ဆင့် ဘာသင်ရမည်နှင့် ဘာလိုအပ်နေသည်။",
    "(optional)": "(မဖြစ်မနေ မဟုတ်ပါ)",
    "Field of study": "ပညာရပ်နယ်ပယ်",
    "Graduation year": "ဘွဲ့ရမည့်နှစ်",

    // --- sign in and register ---------------------------------------------
    "Sign in to continue to InternshipJP.": "InternshipJP သို့ ဆက်လက်အသုံးပြုရန် ဝင်ရောက်ပါ။",
    "Sign in": "ဝင်ရောက်ရန်",
    "Signing in...": "ဝင်ရောက်နေသည်...",
    "New to InternshipJP?": "InternshipJP တွင် အသစ်လား။",
    "Sign up": "အကောင့်ဖွင့်ရန်",
    "Create your account": "အကောင့် ဖန်တီးပါ",
    "Find opportunities, or find people to hire.": "အခွင့်အလမ်းများ ရှာပါ၊ သို့မဟုတ် ခေါ်ယူမည့်သူများ ရှာပါ။",
    "Create account": "အကောင့် ဖန်တီးရန်",
    "Creating your account...": "အကောင့် ဖန်တီးနေသည်...",
    "Already have an account?": "အကောင့် ရှိပြီးသားလား။",

    // --- notification types ------------------------------------------------
    "Certificates": "လက်မှတ်များ",
    "Applications": "လျှောက်လွှာများ",
    "Companies": "ကုမ္ပဏီများ",
    "Account": "အကောင့်",
    "System": "စနစ်",
    "All": "အားလုံး",
    "Today": "ယနေ့",
    "This week": "ဤအပတ်",
    "Nothing unread": "မဖတ်ရသေးသည် မရှိပါ",
    "You are up to date.": "အားလုံး ဖတ်ပြီးပါပြီ။",
    "No notifications yet": "အသိပေးချက် မရှိသေးပါ",

    // --- reports page sections --------------------------------------------
    "Platform": "စနစ်",
    "Who is on it, and what is stuck.": "မည်သူများ ရှိပြီး ဘာတွေ ရပ်တန့်နေသလဲ။",
    "Review queues": "စိစစ်ရန် စာရင်းများ",
    "What is waiting for a decision, and for how long.": "ဆုံးဖြတ်ချက် စောင့်ဆိုင်းနေသည်များနှင့် ကြာချိန်။",
    "Oldest pending work": "အကြာဆုံး စောင့်ဆိုင်းနေသော အလုပ်",
    "The item in each queue that has waited longest.": "စာရင်းတစ်ခုစီတွင် အကြာဆုံး စောင့်ဆိုင်းနေသည့် အရာ။",
    "AI activity": "AI လုပ်ဆောင်မှု",
    "Every call the assistants made, and whether it succeeded.": "အကူအညီများ ခေါ်ဆိုခဲ့သည့် အကြိမ်တိုင်းနှင့် အောင်မြင်မှု အခြေအနေ။",
    "Nothing waiting.": "စောင့်ဆိုင်းနေသည် မရှိပါ။",

    // --- company listing issues -------------------------------------------
    // CompanyInsightService sends each of these with a code beside it, so the
    // set is fixed and can be looked up on the way out.
    "No requirements written": "လိုအပ်ချက်များ မရေးထားပါ",
    "No responsibilities written": "တာဝန်များ မရေးထားပါ",
    "No required skills, so students cannot be matched to it": "လိုအပ်သော ကျွမ်းကျင်မှု မသတ်မှတ်ထားသဖြင့် ကျောင်းသားများနှင့် တွဲပေး၍ မရပါ",
    "No stipend information, which reduces applications": "ထောက်ပံ့ကြေး အချက်အလက် မရှိသဖြင့် လျှောက်ထားမှု နည်းစေပါသည်",
    "No application deadline": "လျှောက်လွှာ ပိတ်ရက် မသတ်မှတ်ထားပါ",
    "Deadline has passed but the vacancy is still open": "ပိတ်ရက် ကျော်လွန်သွားပြီ ဖြစ်သော်လည်း နေရာမှာ ဖွင့်ထားဆဲ ဖြစ်သည်",
    "Open but has received no applications": "ဖွင့်ထားသော်လည်း လျှောက်လွှာ တစ်ခုမျှ မရရှိသေးပါ",
    "Still a draft, so no student can see it": "မူကြမ်း အဆင့်တွင်သာ ရှိသေးသဖြင့် ကျောင်းသားများ မမြင်ရပါ",

    // --- admin dashboard panels ------------------------------------------
    "User management": "အသုံးပြုသူ စီမံခန့်ခွဲမှု",
    "Configuration": "ပြင်ဆင်မှု",
    "Configured": "ပြင်ဆင်ပြီး",
    "Not configured": "မပြင်ဆင်ရသေး",
    "EMPLOYER": "အလုပ်ရှင်",
    "ADMIN": "စီမံခန့်ခွဲသူ",
    "Administrator": "စီမံခန့်ခွဲသူ",
    "Employer": "အလုပ်ရှင်",
    "View all": "အားလုံး ကြည့်ရန်",
    "View": "ကြည့်ရန်",
    "Mark all read": "အားလုံး ဖတ်ပြီးအဖြစ် မှတ်ရန်",
    "Mark read": "ဖတ်ပြီး",
    "Nothing new.": "အသစ် မရှိပါ။",
    "View all notifications": "အသိပေးချက် အားလုံး ကြည့်ရန်",
    "Close": "ပိတ်ရန်",
    "Save changes": "သိမ်းဆည်းရန်",
    "Search": "ရှာရန်",
    "Sign out": "ထွက်ရန်",
    "Download": "ဒေါင်းလုဒ်",
    "Open in a tab": "တက်ဘ်တွင် ဖွင့်ရန်",
    "Back to queue": "စာရင်းသို့ ပြန်သွားရန်",
    "Back to list": "စာရင်းသို့ ပြန်သွားရန်",
    "Back to applicants": "လျှောက်ထားသူများသို့ ပြန်သွားရန်",
    "Previous": "ယခင်",
    "Next": "နောက်တစ်ခု",

    // --- notification titles ---------------------------------------------
    // The backend picks each of these from a fixed set, so they can be looked
    // up on the way out. The MESSAGE beneath cannot: it carries names and
    // quoted values built at the moment the event happened.
    "Certificate waiting for verification": "စိစစ်ရန် စောင့်ဆိုင်းနေသော လက်မှတ်",
    "New company waiting for approval": "အတည်ပြုရန် စောင့်ဆိုင်းနေသော ကုမ္ပဏီ အသစ်",
    "Company review completed": "ကုမ္ပဏီ စိစစ်မှု ပြီးဆုံးပြီ",
    "Your account status changed": "သင့် အကောင့် အခြေအနေ ပြောင်းလဲသွားပါပြီ",
    "Your application was updated": "သင့် လျှောက်လွှာ အခြေအနေ ပြောင်းလဲသွားပါပြီ",
    "Certificate verified": "လက်မှတ် စိစစ်ပြီးပါပြီ",
    "Certificate rejected": "လက်မှတ် ငြင်းပယ်ခံရပါသည်",

    // --- table headers, status words and the AI pages ---------------------
    // These reach the screen through DataTable, StatusBadge and the assistant
    // panels rather than through PageHeader, which is why they needed a
    // separate pass.

    // Table headers
    "Certificate": "လက်မှတ်",
    "Internship": "အလုပ်သင်နေရာ",
    "Action": "လုပ်ဆောင်ချက်",
    "Created": "ဖန်တီးသည့်ရက်",
    "Registered": "မှတ်ပုံတင်သည့်ရက်",
    "Last login": "နောက်ဆုံး ဝင်ရောက်မှု",
    "Waiting since": "စောင့်ဆိုင်းနေသည်မှာ",
    "Duration": "ကြာချိန်",
    "Positions": "နေရာအရေအတွက်",
    "Work mode": "အလုပ်ပုံစံ",
    "Registration": "မှတ်ပုံတင်အမှတ်",
    "Feature": "လုပ်ဆောင်ချက်",
    "Model": "မော်ဒယ်",
    "Result": "ရလဒ်",
    "Tokens": "Tokens",
    "Time": "အချိန်",

    // Status words - StatusBadge capitalises before looking up
    "Pending": "စောင့်ဆိုင်းဆဲ",
    "Verified": "စိစစ်ပြီး",
    "Rejected": "ငြင်းပယ်ပြီး",
    "Approved": "အတည်ပြုပြီး",
    "Active": "အသက်ဝင်နေသည်",
    "Draft": "မူကြမ်း",
    "Closed": "ပိတ်ထားသည်",
    "Filled": "နေရာပြည့်ပြီ",
    "Under review": "စိစစ်နေဆဲ",
    "Shortlisted": "ရွေးချယ်ခံရသည်",
    "Interview": "အင်တာဗျူး",
    "Withdrawn": "ရုပ်သိမ်းပြီး",

    // Assistant tabs and sections
    "Chat": "စကားပြော",
    "Matches": "ကိုက်ညီမှုများ",
    "What to learn": "ဘာသင်ယူရမလဲ",
    "What to learn next": "နောက်တစ်ဆင့် ဘာသင်ယူရမလဲ",
    "My company": "ကျွန်ုပ်၏ ကုမ္ပဏီ",
    "New conversation": "စကားပြောဆိုမှု အသစ်",
    "Send": "ပို့ရန်",
    "Refresh": "ပြန်လည်ရယူရန်",
    "Refresh recommendations": "အကြံပြုချက်များ ပြန်ရယူရန်",
    "Ask AI": "AI ကို မေးရန်",
    "Ask about this": "ဤအကြောင်း မေးရန်",
    "Learn how": "ဘယ်လိုသင်ရမလဲ",
    "To learn": "သင်ယူရန်",
    "You have": "သင့်တွင် ရှိပြီးသား",
    "Suggested order": "အကြံပြု အစီအစဉ်",
    "Fix these first": "ဤအရာများကို ဦးစွာ ပြင်ပါ",
    "Matched to your skills": "သင့် ကျွမ်းကျင်မှုနှင့် ကိုက်ညီသည်",
    "Employers are asking for what you have": "အလုပ်ရှင်များ တောင်းဆိုနေသော သင့်တွင်ရှိပြီးသား ကျွမ်းကျင်မှုများ",
    "Listings that need attention": "အာရုံစိုက်ရန် လိုအပ်သော ကြေညာချက်များ",
    "Your company at a glance": "သင့်ကုမ္ပဏီ အနှစ်ချုပ်",
    "Ask the assistant to explain this": "ဤအကြောင်း ရှင်းပြရန် အကူအညီကို မေးပါ",
    "Ask the assistant to plan my session": "ယနေ့ အလုပ်အစီအစဉ် ရေးဆွဲပေးရန် မေးပါ",

    // --- second pass: the remaining 95 -----------------------------------
    // Product names (Frontend, MariaDB, LinkedIn, GitHub, AI) stay in English
    // on purpose - they are proper nouns, and transliterating them would make
    // the Integration page harder to read, not easier.

    "AI provider": "AI ဝန်ဆောင်မှုပေးသူ",
    "AI usage": "AI အသုံးပြုမှု",
    "Account type": "အကောင့် အမျိုးအစား",
    "Add, update, or remove your education records.": "သင့် ပညာရေး မှတ်တမ်းများကို ထည့်ရန်၊ ပြင်ရန် သို့မဟုတ် ဖျက်ရန်။",
    "Add, update, or remove your skills.": "သင့် ကျွမ်းကျင်မှုများကို ထည့်ရန်၊ ပြင်ရန် သို့မဟုတ် ဖျက်ရန်။",
    "Applications no employer has opened": "အလုပ်ရှင် မဖွင့်ရသေးသော လျှောက်လွှာများ",
    "Approval decisions and platform events for your administrator account.": "သင့် စီမံခန့်ခွဲသူ အကောင့်အတွက် အတည်ပြုချက်များနှင့် စနစ်ဆိုင်ရာ အဖြစ်အပျက်များ။",
    "Ask a question and it will be saved here.": "မေးခွန်း တစ်ခု မေးပါ။ ဤနေရာတွင် သိမ်းဆည်းထားပါမည်။",
    "Ask the assistant a question": "အကူအညီကို မေးခွန်း တစ်ခု မေးပါ",
    "Assistant mode": "အကူအညီ ပုံစံ",
    "At least 8 characters.": "အနည်းဆုံး စာလုံး ၈ လုံး။",
    "Availability": "အားလပ်ချိန်",
    "Backend API": "Backend API",
    "Certificate preview": "လက်မှတ် အစမ်းကြည့်ရှုခြင်း",
    "Certificate verification queue": "လက်မှတ် စိစစ်ရန် စာရင်း",
    "Certificates pending": "စောင့်ဆိုင်းနေသော လက်မှတ်များ",
    "Certificates waiting longest": "အကြာဆုံး စောင့်ဆိုင်းနေသော လက်မှတ်များ",
    "Check the registration before activating this company's recruiters.": "ဤကုမ္ပဏီ၏ အကောင့်များ အသက်မဝင်မီ မှတ်ပုံတင်မှုကို စိစစ်ပါ။",
    "Checking what is waiting for you...": "သင့်အတွက် စောင့်ဆိုင်းနေသည်များကို စစ်ဆေးနေသည်...",
    "Checking your company's status...": "သင့်ကုမ္ပဏီ၏ အခြေအနေကို စစ်ဆေးနေသည်...",
    "Checking your session...": "သင့် session ကို စစ်ဆေးနေသည်...",
    "Companies pending": "စောင့်ဆိုင်းနေသော ကုမ္ပဏီများ",
    "Company website": "ကုမ္ပဏီ ဝဘ်ဆိုက်",
    "Create a vacancy for your company.": "သင့်ကုမ္ပဏီအတွက် အလုပ်နေရာ တစ်ခု ဖန်တီးပါ။",
    "Delete this certificate": "ဤလက်မှတ်ကို ဖျက်ရန်",
    "Delete this conversation": "ဤစကားပြောဆိုမှုကို ဖျက်ရန်",
    "Edit organisation details": "ကုမ္ပဏီ အချက်အလက် ပြင်ဆင်ရန်",
    "Edit this internship": "ဤအလုပ်သင်နေရာကို ပြင်ဆင်ရန်",
    "Education information": "ပညာရေး အချက်အလက်",
    "Employer assistant": "အလုပ်ရှင် အကူအညီ",
    "Failed": "မအောင်မြင်ပါ",
    "Finding internships that match your skills...": "သင့် ကျွမ်းကျင်မှုနှင့် ကိုက်ညီသော နေရာများ ရှာဖွေနေသည်...",
    "Foundation complete": "အခြေခံ ပြီးစီးပြီ",
    "Frontend": "Frontend",
    "GitHub": "GitHub",
    "Internship preferences": "အလုပ်သင်နေရာ ရွေးချယ်မှုများ",
    "It only ever reads data belonging to the signed-in user, so it needs a session. The real login screen is Member 2's work; until then, use the Session panel on the Integration status page.": "၎င်းသည် ဝင်ရောက်ထားသူ၏ အချက်အလက်များကိုသာ ဖတ်ရှုသောကြောင့် session လိုအပ်ပါသည်။ အမှန်တကယ် ဝင်ရောက်သည့် စာမျက်နှာမှာ Member 2 ၏ တာဝန်ဖြစ်သည်။ ထိုအချိန်အထိ စနစ် အခြေအနေ စာမျက်နှာရှိ Session ကို အသုံးပြုပါ။",
    "Live check of the connections between React, Spring Boot, MariaDB and the AI provider.": "React, Spring Boot, MariaDB နှင့် AI ဝန်ဆောင်မှုကြား ချိတ်ဆက်မှုကို တိုက်ရိုက် စစ်ဆေးခြင်း။",
    "Loading account settings...": "အကောင့် ဆက်တင်များ ရယူနေသည်...",
    "Loading administrator dashboard...": "စီမံခန့်ခွဲသူ ဒက်ရှ်ဘုတ် ရယူနေသည်...",
    "Loading applicants...": "လျှောက်ထားသူများ ရယူနေသည်...",
    "Loading internships...": "အလုပ်သင်နေရာများ ရယူနေသည်...",
    "Loading reports...": "အစီရင်ခံစာများ ရယူနေသည်...",
    "Loading the application...": "လျှောက်လွှာ ရယူနေသည်...",
    "Loading the certificate...": "လက်မှတ် ရယူနေသည်...",
    "Loading the company...": "ကုမ္ပဏီ အချက်အလက် ရယူနေသည်...",
    "Loading the internship...": "အလုပ်သင်နေရာ ရယူနေသည်...",
    "Loading users...": "အသုံးပြုသူများ ရယူနေသည်...",
    "Loading your account...": "သင့် အကောင့် ရယူနေသည်...",
    "Loading your company...": "သင့် ကုမ္ပဏီ ရယူနေသည်...",
    "Loading your internships...": "သင့် အလုပ်သင်နေရာများ ရယူနေသည်...",
    "Loading your notifications...": "သင့် အသိပေးချက်များ ရယူနေသည်...",
    "Manage your recruiter information.": "သင့် အလုပ်ခေါ်ယူသူ အချက်အလက်ကို စီမံရန်။",
    "MariaDB": "MariaDB",
    "No open internships to match yet": "ကိုက်ညီရန် ဖွင့်ထားသော နေရာ မရှိသေးပါ",
    "Once employers publish vacancies, they will be scored against the skills on your profile.": "အလုပ်ရှင်များ နေရာများ ကြေညာသည်နှင့် သင့်ပရိုဖိုင်ရှိ ကျွမ်းကျင်မှုများနှင့် နှိုင်းယှဉ် အမှတ်ပေးပါမည်။",
    "Open the uploaded file": "တင်ထားသော ဖိုင်ကို ဖွင့်ရန်",
    "Open the uploaded file and verify the qualification before employers can see it.": "အလုပ်ရှင်များ မမြင်မီ တင်ထားသော ဖိုင်ကို ဖွင့်၍ အရည်အချင်းကို စိစစ်ပါ။",
    "Opening the certificate...": "လက်မှတ်ကို ဖွင့်နေသည်...",
    "Or pick one of the suggestions below to get started.": "သို့မဟုတ် အောက်ပါ အကြံပြုချက်တစ်ခုကို ရွေးပြီး စတင်ပါ။",
    "Pending company approvals": "အတည်ပြုရန် စောင့်ဆိုင်းနေသော ကုမ္ပဏီများ",
    "Platform workload, review queues and AI operational activity.": "စနစ်၏ အလုပ်ပမာဏ၊ စိစစ်ရန် စာရင်းများနှင့် AI လုပ်ဆောင်မှုများ။",
    "Portfolio": "Portfolio",
    "Post a vacancy first, and applicants will appear here.": "ဦးစွာ အလုပ်နေရာ တင်ပါ။ လျှောက်ထားသူများ ဤနေရာတွင် ပေါ်လာပါမည်။",
    "Profile": "ပရိုဖိုင်",
    "Profile completeness": "ပရိုဖိုင် ပြည့်စုံမှု",
    "Provider": "ဝန်ဆောင်မှုပေးသူ",
    "Recent registrations": "မကြာသေးမီက မှတ်ပုံတင်မှုများ",
    "Reviewing your listings and pipeline...": "သင့် ကြေညာချက်များနှင့် လုပ်ငန်းစဉ်ကို သုံးသပ်နေသည်...",
    "Search users": "အသုံးပြုသူများ ရှာရန်",
    "Session": "Session",
    "Sign in or register": "ဝင်ရောက်ရန် သို့မဟုတ် မှတ်ပုံတင်ရန်",
    "Sign in to use the assistant": "အကူအညီ အသုံးပြုရန် ဝင်ရောက်ပါ",
    "Signed in as": "ဝင်ရောက်ထားသူ",
    "Student assistant": "ကျောင်းသား အကူအညီ",
    "Successful": "အောင်မြင်သည်",
    "The assistant is preparing an answer": "အကူအညီမှ အဖြေ ပြင်ဆင်နေသည်",
    "This assistant is for a different role": "ဤအကူအညီမှာ အခြား အခန်းကဏ္ဍအတွက် ဖြစ်သည်",
    "Total calls": "ခေါ်ဆိုမှု စုစုပေါင်း",
    "Update your personal information and internship preferences.": "သင့် ကိုယ်ရေးအချက်အလက်နှင့် အလုပ်သင်နေရာ ရွေးချယ်မှုများကို ပြင်ဆင်ရန်။",
    "View all internships created on the platform.": "စနစ်တွင် ဖန်တီးထားသော အလုပ်သင်နေရာ အားလုံးကို ကြည့်ရန်။",
    "View applicants": "လျှောက်ထားသူများ ကြည့်ရန်",
    "What needs attention": "အာရုံစိုက်ရန် လိုအပ်သည်များ",
    "Working out your skill gaps...": "သင့် ကျွမ်းကျင်မှု ကွာဟချက်များကို တွက်ချက်နေသည်...",
    "Workload": "အလုပ်ပမာဏ",
    "Your account, password and sign-in security.": "သင့် အကောင့်၊ စကားဝှက်နှင့် ဝင်ရောက်မှု လုံခြုံရေး။",
    "Your administrator account and security.": "သင့် စီမံခန့်ခွဲသူ အကောင့်နှင့် လုံခြုံရေး။",
    "Your job title": "သင့် ရာထူး",
    "Your organisation's details, and where its approval stands.": "သင့်ကုမ္ပဏီ၏ အချက်အလက်နှင့် အတည်ပြုချက် အခြေအနေ။",
    "Your question": "သင့် မေးခွန်း",

    // ---------------------------------------------------------------------
    // TRANSLATED BY ENGLISH SOURCE
    //
    // Everything below is keyed on the English string itself rather than on a
    // key like "nav.dashboard". That is how gettext works, and it is why the
    // 25 pages did not have to be edited: PageHeader, StatCard, EmptyState,
    // SectionCard and LoadingBlock run their text through t(), and t() returns
    // the English unchanged when there is no entry here.
    //
    // So adding a translation is adding a line to this list. Removing one puts
    // the English back. Nothing else has to change.
    // ---------------------------------------------------------------------

    // Page titles
    "Dashboard": "ဒက်ရှ်ဘုတ်",
    "Browse internships": "အလုပ်သင်နေရာများ ရှာရန်",
    "My applications": "ကျွန်ုပ်၏ လျှောက်လွှာများ",
    "My certificates": "ကျွန်ုပ်၏ လက်မှတ်များ",
    "Notifications": "အသိပေးချက်များ",
    "Settings": "ဆက်တင်များ",
    "Post an internship": "အလုပ်သင်နေရာ တင်ရန်",
    "Manage internships": "အလုပ်သင်နေရာများ စီမံရန်",
    "Company profile": "ကုမ္ပဏီ ပရိုဖိုင်",
    "Internships": "အလုပ်သင်နေရာများ",
    "Users": "အသုံးပြုသူများ",
    "Reports": "အစီရင်ခံစာများ",
    "Integration status": "စနစ် အခြေအနေ",

    // Dashboard cards
    "Students": "ကျောင်းသားများ",
    "Employers": "အလုပ်ရှင်များ",
    "Administrators": "စီမံခန့်ခွဲသူများ",
    "Suspended accounts": "ရပ်ဆိုင်းထားသော အကောင့်များ",
    "Suspended": "ရပ်ဆိုင်းထားသည်",
    "Pending companies": "စောင့်ဆိုင်းနေသော ကုမ္ပဏီများ",
    "Pending certificates": "စောင့်ဆိုင်းနေသော လက်မှတ်များ",
    "Stalled applications": "ရပ်တန့်နေသော လျှောက်လွှာများ",
    "Stalled": "ရပ်တန့်နေသည်",
    "Open vacancies": "ဖွင့်ထားသော နေရာများ",
    "Open internships": "ဖွင့်ထားသော အလုပ်သင်နေရာများ",
    "Total applicants": "လျှောက်ထားသူ စုစုပေါင်း",
    "Accepted": "လက်ခံပြီး",
    "Conversion": "အောင်မြင်နှုန်း",
    "Profile complete": "ပရိုဖိုင် ပြည့်စုံမှု",
    "Verified certificates": "စိစစ်ပြီး လက်မှတ်များ",

    // Card hints
    "All registered student accounts": "မှတ်ပုံတင်ထားသော ကျောင်းသား အကောင့်အားလုံး",
    "All registered employer accounts": "မှတ်ပုံတင်ထားသော အလုပ်ရှင် အကောင့်အားလုံး",
    "Administrator accounts": "စီမံခန့်ခွဲသူ အကောင့်များ",
    "Accounts currently suspended": "လက်ရှိ ရပ်ဆိုင်းထားသော အကောင့်များ",
    "Companies waiting for approval": "အတည်ပြုချက် စောင့်ဆိုင်းနေသော ကုမ္ပဏီများ",
    "Certificates waiting for verification": "စိစစ်မှု စောင့်ဆိုင်းနေသော လက်မှတ်များ",
    "Currently accepting applications": "လက်ရှိ လျှောက်လွှာ လက်ခံနေသည်",
    "Applications received": "လက်ခံရရှိသော လျှောက်လွှာများ",
    "Candidates accepted": "လက်ခံခဲ့သော လျှောက်ထားသူများ",
    "Applicants accepted": "လက်ခံခဲ့သော လျှောက်ထားသူများ",
    "Internships you have applied to": "သင် လျှောက်ထားခဲ့သော အလုပ်သင်နေရာများ",
    "Only verified ones reach employers": "စိစစ်ပြီးသည်များသာ အလုပ်ရှင်ထံ ရောက်ပါသည်",

    // Subtitles
    "An overview of your hiring.": "သင်၏ ဝန်ထမ်းခေါ်ယူမှု အနှစ်ချုပ်။",
    "An overview of your internship search.": "သင်၏ အလုပ်သင်နေရာ ရှာဖွေမှု အနှစ်ချုပ်။",
    "Platform overview and work waiting for review.": "စနစ် အနှစ်ချုပ်နှင့် စိစစ်ရန် စောင့်ဆိုင်းနေသော အလုပ်များ။",
    "Every internship you have applied to, and where it stands.": "သင် လျှောက်ထားခဲ့သော အလုပ်သင်နေရာများနှင့် ၎င်းတို့၏ အခြေအနေ။",
    "Every vacancy currently accepting applications.": "လက်ရှိ လျှောက်လွှာ လက်ခံနေသော နေရာအားလုံး။",
    "Every vacancy your company owns, and where each one stands.": "သင့်ကုမ္ပဏီပိုင် နေရာအားလုံးနှင့် ၎င်းတို့၏ အခြေအနေ။",
    "Everyone who applied, and where each one stands.": "လျှောက်ထားသူအားလုံးနှင့် ၎င်းတို့၏ အခြေအနေ။",
    "Updates on your applications, approvals and account.": "သင့် လျှောက်လွှာများ၊ အတည်ပြုချက်များနှင့် အကောင့်ဆိုင်ရာ အချက်အလက်များ။",
    "What employers see when you apply.": "သင် လျှောက်ထားသည့်အခါ အလုပ်ရှင်များ မြင်ရမည့် အချက်များ။",
    "Manage student and employer accounts and their status.": "ကျောင်းသားနှင့် အလုပ်ရှင် အကောင့်များနှင့် ၎င်းတို့၏ အခြေအနေကို စီမံရန်။",
    "Review company registrations before their recruiter accounts become active.": "ကုမ္ပဏီ မှတ်ပုံတင်မှုများကို ၎င်းတို့၏ အကောင့်များ အသက်ဝင်မလာမီ စိစစ်ပါ။",
    "Upload a qualification, and an administrator verifies it before employers see it.": "အရည်အချင်း လက်မှတ် တင်ပါ။ အလုပ်ရှင်များ မမြင်မီ စီမံခန့်ခွဲသူက စိစစ်ပါမည်။",

    // Section and field headings
    "Personal information": "ကိုယ်ရေးအချက်အလက်",
    "Organisation details": "ကုမ္ပဏီ အချက်အလက်",
    "Skills": "ကျွမ်းကျင်မှုများ",
    "Your skills": "သင်၏ ကျွမ်းကျင်မှုများ",
    "Education": "ပညာရေး",
    "Your education": "သင်၏ ပညာရေး",
    "Links": "လင့်ခ်များ",
    "About": "အကြောင်း",
    "Cover letter": "လျှောက်လွှာ စာ",
    "History": "မှတ်တမ်း",
    "Password": "စကားဝှက်",
    "Status": "အခြေအနေ",
    "Email": "အီးမေးလ်",
    "Country": "နိုင်ငံ",
    "City": "မြို့",
    "Age": "အသက်",
    "Date of birth": "မွေးသက္ကရာဇ်",
    "Degree": "ဘွဲ့",
    "Role": "အခန်းကဏ္ဍ",
    "Student": "ကျောင်းသား",
    "Description": "ဖော်ပြချက်",
    "Requirements": "လိုအပ်ချက်များ",
    "Responsibilities": "တာဝန်များ",
    "Issuer": "ထုတ်ပေးသူ",
    "Issue date": "ထုတ်ပေးသည့်ရက်",
    "Uploaded": "တင်ပြီးသည့်အချိန်",
    "File": "ဖိုင်",
    "Size": "အရွယ်အစား",
    "Applied": "လျှောက်ထားပြီး",
    "Company name": "ကုမ္ပဏီ အမည်",
    "Available from": "စတင်နိုင်သည့်ရက်",
    "Preferred work mode": "နှစ်သက်သော အလုပ်ပုံစံ",
    "New password": "စကားဝှက် အသစ်",
    "Current password": "လက်ရှိ စကားဝှက်",
    "Confirm new password": "စကားဝှက် အသစ် အတည်ပြုရန်",
    "Change password": "စကားဝှက် ပြောင်းရန်",
    "Edit skills": "ကျွမ်းကျင်မှုများ ပြင်ဆင်ရန်",
    "Edit education": "ပညာရေး ပြင်ဆင်ရန်",
    "Upload a certificate": "လက်မှတ် တင်ရန်",

    // Empty states
    "No internships yet": "အလုပ်သင်နေရာ မရှိသေးပါ",
    "No conversations yet": "စကားပြောဆိုမှု မရှိသေးပါ",
    "No certificates yet": "လက်မှတ် မရှိသေးပါ",

    // Loading
    "Loading your figures...": "ကိန်းဂဏန်းများ ရယူနေသည်...",
    "Loading your applications...": "သင့် လျှောက်လွှာများ ရယူနေသည်...",
    "Loading your certificates...": "သင့် လက်မှတ်များ ရယူနေသည်...",
    "Loading your profile...": "သင့် ပရိုဖိုင် ရယူနေသည်...",
    "Loading open internships...": "ဖွင့်ထားသော နေရာများ ရယူနေသည်...",
    "Loading the queue...": "စာရင်း ရယူနေသည်...",

    "nav.dashboard": "ဒက်ရှ်ဘုတ်",
    "nav.browse": "အလုပ်သင်နေရာများ ရှာရန်",
    "nav.applications": "ကျွန်ုပ်၏ လျှောက်လွှာများ",
    "nav.certificates": "လက်မှတ်များ",
    "nav.notifications": "အသိပေးချက်များ",
    "nav.ai": "AI အကူအညီ",
    "nav.profile": "ကျွန်ုပ်၏ ပရိုဖိုင်",
    "nav.settings": "ဆက်တင်များ",
    "nav.post": "အလုပ်သင်နေရာ တင်ရန်",
    "nav.manage": "အလုပ်သင်နေရာများ စီမံရန်",
    "nav.applicants": "လျှောက်ထားသူများ",
    "nav.company": "ကုမ္ပဏီ ပရိုဖိုင်",
    "nav.certificateReview": "လက်မှတ် စိစစ်ခြင်း",
    "nav.companies": "ကုမ္ပဏီများ",
    "nav.internships": "အလုပ်သင်နေရာများ",
    "nav.users": "အသုံးပြုသူများ",
    "nav.reports": "အစီရင်ခံစာများ",
    "nav.integration": "စနစ် အခြေအနေ",

    "section.inbox": "စာများ",
    "section.yourSearch": "သင်၏ ရှာဖွေမှု",
    "section.hiring": "ဝန်ထမ်းခေါ်ယူမှု",
    "section.platform": "စနစ်",
    "section.assistant": "အကူအညီ",
    "section.account": "အကောင့်",
    "section.developer": "ဆော့ဖ်ဝဲရေးသားသူ",

    "action.refresh": "ပြန်လည်ရယူရန်",
    "action.save": "သိမ်းဆည်းရန်",
    "action.cancel": "ပယ်ဖျက်ရန်",
    "action.close": "ပိတ်ရန်",
    "action.edit": "ပြင်ဆင်ရန်",
    "action.view": "ကြည့်ရန်",
    "action.apply": "လျှောက်ထားရန်",
    "action.send": "ပို့ရန်",
    "action.search": "ရှာရန်",
    "action.signOut": "ထွက်ရန်",
    "action.markAllRead": "အားလုံး ဖတ်ပြီးအဖြစ် မှတ်ရန်",
    "action.markRead": "ဖတ်ပြီး",

    "bell.title": "အသိပေးချက်များ",
    "bell.empty": "အသစ် မရှိပါ။",
    "bell.viewAll": "အသိပေးချက် အားလုံး ကြည့်ရန်",
    "bell.unread": "မဖတ်ရသေး",

    "lang.label": "ဘာသာစကား",
    "lang.english": "English",
    "lang.burmese": "မြန်မာ",

    "theme.label": "အသွင်အပြင်",
    "theme.system": "စက်အတိုင်း",
    "theme.light": "အလင်း",
    "theme.dark": "အမှောင်",

    "role.student": "ကျောင်းသား",
    "role.employer": "အလုပ်ရှင်",
    "role.admin": "စီမံခန့်ခွဲသူ",
  },
};
